<?php

namespace Database\Seeders;

use App\Models\Loan;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LoanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key constraints
        DB::statement('SET FOREIGN_KEY_CHECKS=0');

        // Clear existing loans
        DB::table('loans')->truncate();

        // Get user IDs for member numbers
        $memberToUserMap = DB::table('users')
            ->whereNotNull('member_number')
            ->pluck('id', 'member_number')
            ->toArray();

        $loansData = [
            // Row 1
            [
                'loan_number' => 'LN001',
                'member_number' => 'PRM2',
                'loan_product_id' => null,
                'principal_amount' => 2052525.00,
                'interest_rate' => 0.00,
                'term_months' => 3,
                'application_date' => '2024-03-26',
                'approval_date' => '2024-03-26',
                'disbursement_date' => '2024-03-26',
                'maturity_date' => '2024-05-26',
                'monthly_payment' => 354402.69,
                'total_amount_due' => 1063208.07,
                'amount_paid' => 0.00,
                'balance' => 1063208.07,
                'status' => 'paid',
                'purpose' => 'personal',
                'guarantor' => null,
                'notes' => 'Staff Loan - New',
            ],
            // Row 2
            [
                'loan_number' => 'LN002',
                'member_number' => 'ASC22',
                'loan_product_id' => null,
                'principal_amount' => 1850505.05,
                'interest_rate' => 0.00,
                'term_months' => 12,
                'application_date' => '2024-03-20',
                'approval_date' => '2024-03-20',
                'disbursement_date' => '2024-03-20',
                'maturity_date' => '2025-02-20',
                'monthly_payment' => 179930.77,
                'total_amount_due' => 2159169.29,
                'amount_paid' => 2159169.29,
                'balance' => 2020.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Michael Paul',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 3
            [
                'loan_number' => 'LN003',
                'member_number' => 'ASC71',
                'loan_product_id' => null,
                'principal_amount' => 1244444.20,
                'interest_rate' => 0.00,
                'term_months' => 11,
                'application_date' => '2024-03-26',
                'approval_date' => '2024-03-26',
                'disbursement_date' => '2024-03-26',
                'maturity_date' => '2025-02-26',
                'monthly_payment' => 121001.46,
                'total_amount_due' => 1331016.06,
                'amount_paid' => 1331016.06,
                'balance' => 1851.85,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Mary Mwinuka',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 4
            [
                'loan_number' => 'LN004',
                'member_number' => 'ASC66',
                'loan_product_id' => null,
                'principal_amount' => 1042424.24,
                'interest_rate' => 0.00,
                'term_months' => 2,
                'application_date' => '2024-03-20',
                'approval_date' => '2024-03-20',
                'disbursement_date' => '2024-03-20',
                'maturity_date' => '2024-05-20',
                'monthly_payment' => 361964.44,
                'total_amount_due' => 723928.88,
                'amount_paid' => 723928.88,
                'balance' => 2020.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Emmanuel Elioth Lulandala',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 5
            [
                'loan_number' => 'LN005',
                'member_number' => 'PRM2',
                'loan_product_id' => null,
                'principal_amount' => 8203505.05,
                'interest_rate' => 0.00,
                'term_months' => 6,
                'application_date' => '2024-04-26',
                'approval_date' => '2024-04-26',
                'disbursement_date' => '2024-04-26',
                'maturity_date' => '2024-10-26',
                'monthly_payment' => 277096.17,
                'total_amount_due' => 1662577.02,
                'amount_paid' => 1662577.02,
                'balance' => 0.00,
                'status' => 'paid',
                'purpose' => 'personal',
                'guarantor' => null,
                'notes' => 'Staff Loan - Top Up',
            ],
            // Row 6
            [
                'loan_number' => 'LN006',
                'member_number' => 'FND6',
                'loan_product_id' => null,
                'principal_amount' => 2140161.62,
                'interest_rate' => 0.00,
                'term_months' => 40,
                'application_date' => '2022-04-26',
                'approval_date' => '2022-04-26',
                'disbursement_date' => '2022-04-26',
                'maturity_date' => '2025-07-26',
                'monthly_payment' => 70707.09,
                'total_amount_due' => 2828283.60,
                'amount_paid' => 2828283.60,
                'balance' => 0.00,
                'status' => 'paid',
                'purpose' => 'personal',
                'guarantor' => null,
                'notes' => 'Normal Loan - Restructured',
            ],
            // Row 7
            [
                'loan_number' => 'LN007',
                'member_number' => 'ORD8',
                'loan_product_id' => null,
                'principal_amount' => 2904505.05,
                'interest_rate' => 0.00,
                'term_months' => 38,
                'application_date' => '2022-05-26',
                'approval_date' => '2022-05-26',
                'disbursement_date' => '2022-05-26',
                'maturity_date' => '2025-06-26',
                'monthly_payment' => 105479.39,
                'total_amount_due' => 4008216.88,
                'amount_paid' => 4008216.88,
                'balance' => 29045.05,
                'status' => 'paid',
                'purpose' => 'personal',
                'guarantor' => null,
                'notes' => 'Normal Loan - Restructured',
            ],
            // Row 8
            [
                'loan_number' => 'LN008',
                'member_number' => 'FND2',
                'loan_product_id' => null,
                'principal_amount' => 10201010.10,
                'interest_rate' => 0.00,
                'term_months' => 24,
                'application_date' => '2022-09-26',
                'approval_date' => '2022-09-26',
                'disbursement_date' => '2022-09-26',
                'maturity_date' => '2024-08-26',
                'monthly_payment' => 557655.22,
                'total_amount_due' => 13383725.28,
                'amount_paid' => 13383725.28,
                'balance' => 1010.10,
                'status' => 'paid',
                'purpose' => 'personal',
                'guarantor' => null,
                'notes' => 'Normal Loan - New',
            ],
            // Row 9
            [
                'loan_number' => 'LN009',
                'member_number' => 'ORD10',
                'loan_product_id' => null,
                'principal_amount' => 10001010.10,
                'interest_rate' => 0.00,
                'term_months' => 24,
                'application_date' => '2022-12-26',
                'approval_date' => '2022-12-26',
                'disbursement_date' => '2022-12-26',
                'maturity_date' => '2024-11-26',
                'monthly_payment' => 546721.89,
                'total_amount_due' => 13121325.36,
                'amount_paid' => 13121325.36,
                'balance' => 79842.93,
                'status' => 'paid',
                'purpose' => 'personal',
                'guarantor' => null,
                'notes' => 'Normal Loan - New',
            ],
            // Row 10
            [
                'loan_number' => 'LN010',
                'member_number' => 'ASC9',
                'loan_product_id' => null,
                'principal_amount' => 1201010.10,
                'interest_rate' => 0.00,
                'term_months' => 17,
                'application_date' => '2023-01-26',
                'approval_date' => '2023-01-26',
                'disbursement_date' => '2023-01-26',
                'maturity_date' => '2024-06-26',
                'monthly_payment' => 48974.52,
                'total_amount_due' => 832566.84,
                'amount_paid' => 832566.84,
                'balance' => 1010.10,
                'status' => 'paid',
                'purpose' => 'personal',
                'guarantor' => null,
                'notes' => 'Normal Loan - New',
            ],
            // Row 11
            [
                'loan_number' => 'LN011',
                'member_number' => 'ASC9',
                'loan_product_id' => null,
                'principal_amount' => 4061010.10,
                'interest_rate' => 0.00,
                'term_months' => 18,
                'application_date' => '2023-04-26',
                'approval_date' => '2023-04-26',
                'disbursement_date' => '2023-04-26',
                'maturity_date' => '2024-10-26',
                'monthly_payment' => 165598.97,
                'total_amount_due' => 2981522.74,
                'amount_paid' => 2981522.74,
                'balance' => 1010.10,
                'status' => 'paid',
                'purpose' => 'personal',
                'guarantor' => null,
                'notes' => 'Normal Loan - New',
            ],
            // Row 12
            [
                'loan_number' => 'LN012',
                'member_number' => 'FND1',
                'loan_product_id' => null,
                'principal_amount' => 5071010.10,
                'interest_rate' => 0.00,
                'term_months' => 34,
                'application_date' => '2023-04-26',
                'approval_date' => '2023-04-26',
                'disbursement_date' => '2023-04-26',
                'maturity_date' => '2026-02-26',
                'monthly_payment' => 206784.52,
                'total_amount_due' => 7030673.68,
                'amount_paid' => 7030673.68,
                'balance' => 0.00,
                'status' => 'paid',
                'purpose' => 'personal',
                'guarantor' => null,
                'notes' => 'Normal Loan - New',
            ],
            // Row 13
            [
                'loan_number' => 'LN013',
                'member_number' => 'ORD5',
                'loan_product_id' => null,
                'principal_amount' => 3051010.10,
                'interest_rate' => 0.00,
                'term_months' => 12,
                'application_date' => '2023-05-26',
                'approval_date' => '2023-05-26',
                'disbursement_date' => '2023-05-26',
                'maturity_date' => '2024-04-26',
                'monthly_payment' => 293913.97,
                'total_amount_due' => 3526967.64,
                'amount_paid' => 3526967.64,
                'balance' => 1010.10,
                'status' => 'paid',
                'purpose' => 'personal',
                'guarantor' => null,
                'notes' => 'Normal Loan - New',
            ],
            // Row 14
            [
                'loan_number' => 'LN014',
                'member_number' => 'PRM4',
                'loan_product_id' => null,
                'principal_amount' => 10121010.10,
                'interest_rate' => 0.00,
                'term_months' => 19,
                'application_date' => '2023-05-26',
                'approval_date' => '2023-05-26',
                'disbursement_date' => '2023-05-26',
                'maturity_date' => '2024-12-26',
                'monthly_payment' => 553281.89,
                'total_amount_due' => 10512198.09,
                'amount_paid' => 10512198.09,
                'balance' => 1010.10,
                'status' => 'paid',
                'purpose' => 'personal',
                'guarantor' => null,
                'notes' => 'Normal Loan - New',
            ],
            // Row 15
            [
                'loan_number' => 'LN015',
                'member_number' => 'PRM2',
                'loan_product_id' => null,
                'principal_amount' => 4061010.10,
                'interest_rate' => 0.00,
                'term_months' => 13,
                'application_date' => '2023-05-26',
                'approval_date' => '2023-05-26',
                'disbursement_date' => '2023-05-26',
                'maturity_date' => '2024-06-26',
                'monthly_payment' => 165598.97,
                'total_amount_due' => 2153734.62,
                'amount_paid' => 2153734.62,
                'balance' => 1010.10,
                'status' => 'paid',
                'purpose' => 'personal',
                'guarantor' => null,
                'notes' => 'Normal Loan - New',
            ],
            // Row 16
            [
                'loan_number' => 'LN016',
                'member_number' => 'ORD6',
                'loan_product_id' => null,
                'principal_amount' => 10121010.10,
                'interest_rate' => 0.00,
                'term_months' => 32,
                'application_date' => '2023-07-26',
                'approval_date' => '2023-07-26',
                'disbursement_date' => '2023-07-26',
                'maturity_date' => '2026-03-26',
                'monthly_payment' => 412712.30,
                'total_amount_due' => 13206793.60,
                'amount_paid' => 13206793.60,
                'balance' => 0.03,
                'status' => 'paid',
                'purpose' => 'personal',
                'guarantor' => null,
                'notes' => 'Normal Loan - New',
            ],
            // Row 17
            [
                'loan_number' => 'LN017',
                'member_number' => 'FND3',
                'loan_product_id' => null,
                'principal_amount' => 4309091.10,
                'interest_rate' => 0.00,
                'term_months' => 27,
                'application_date' => '2023-07-26',
                'approval_date' => '2023-07-26',
                'disbursement_date' => '2023-07-26',
                'maturity_date' => '2025-09-26',
                'monthly_payment' => 175715.16,
                'total_amount_due' => 4744308.94,
                'amount_paid' => 4744308.94,
                'balance' => -0.22,
                'status' => 'paid',
                'purpose' => 'personal',
                'guarantor' => null,
                'notes' => 'Normal Loan - New',
            ],
            // Row 18
            [
                'loan_number' => 'LN018',
                'member_number' => 'ORD4',
                'loan_product_id' => null,
                'principal_amount' => 14157576.10,
                'interest_rate' => 0.00,
                'term_months' => 36,
                'application_date' => '2023-09-26',
                'approval_date' => '2023-09-26',
                'disbursement_date' => '2023-09-26',
                'maturity_date' => '2026-08-26',
                'monthly_payment' => 577314.49,
                'total_amount_due' => 20783321.64,
                'amount_paid' => 20783321.64,
                'balance' => 396222.19,
                'status' => 'active',
                'purpose' => 'personal',
                'guarantor' => null,
                'notes' => 'Normal Loan - New - Continue Follow Up',
            ],
            // Row 19
            [
                'loan_number' => 'LN019',
                'member_number' => 'PRM1',
                'loan_product_id' => null,
                'principal_amount' => 17076976.10,
                'interest_rate' => 0.00,
                'term_months' => 16,
                'application_date' => '2023-11-26',
                'approval_date' => '2023-11-26',
                'disbursement_date' => '2023-11-26',
                'maturity_date' => '2025-03-26',
                'monthly_payment' => 601489.05,
                'total_amount_due' => 9623824.80,
                'amount_paid' => 9623824.80,
                'balance' => 1010.10,
                'status' => 'paid',
                'purpose' => 'personal',
                'guarantor' => null,
                'notes' => 'Normal Loan - New',
            ],
            // Row 20
            [
                'loan_number' => 'LN020',
                'member_number' => 'FND1',
                'loan_product_id' => null,
                'principal_amount' => 2036364.10,
                'interest_rate' => 0.00,
                'term_months' => 13,
                'application_date' => '2024-01-26',
                'approval_date' => '2024-01-26',
                'disbursement_date' => '2024-01-26',
                'maturity_date' => '2025-02-26',
                'monthly_payment' => 111321.24,
                'total_amount_due' => 1447176.12,
                'amount_paid' => 1447176.12,
                'balance' => 1010.10,
                'status' => 'paid',
                'purpose' => 'personal',
                'guarantor' => null,
                'notes' => 'Normal Loan - New',
            ],
            // Row 21
            [
                'loan_number' => 'LN021',
                'member_number' => 'PRM5',
                'loan_product_id' => null,
                'principal_amount' => 9107071.10,
                'interest_rate' => 0.00,
                'term_months' => 18,
                'application_date' => '2024-02-26',
                'approval_date' => '2024-02-26',
                'disbursement_date' => '2024-02-26',
                'maturity_date' => '2025-08-26',
                'monthly_payment' => 371366.12,
                'total_amount_due' => 6684530.10,
                'amount_paid' => 6684530.10,
                'balance' => 1010.10,
                'status' => 'paid',
                'purpose' => 'personal',
                'guarantor' => null,
                'notes' => 'Normal Loan - New',
            ],
            // Row 22
            [
                'loan_number' => 'LN022',
                'member_number' => 'ORD7',
                'loan_product_id' => null,
                'principal_amount' => 10171721.10,
                'interest_rate' => 0.00,
                'term_months' => 17,
                'application_date' => '2024-03-26',
                'approval_date' => '2024-03-26',
                'disbursement_date' => '2024-03-26',
                'maturity_date' => '2025-08-26',
                'monthly_payment' => 553072.07,
                'total_amount_due' => 9402611.85,
                'amount_paid' => 9402611.85,
                'balance' => 1010.10,
                'status' => 'paid',
                'purpose' => 'personal',
                'guarantor' => null,
                'notes' => 'Normal Loan - New',
            ],
            // Row 23
            [
                'loan_number' => 'LN023',
                'member_number' => 'ORD3',
                'loan_product_id' => null,
                'principal_amount' => 6790572.10,
                'interest_rate' => 0.00,
                'term_months' => 12,
                'application_date' => '2024-02-26',
                'approval_date' => '2024-02-26',
                'disbursement_date' => '2024-02-26',
                'maturity_date' => '2025-01-26',
                'monthly_payment' => 654158.45,
                'total_amount_due' => 7849901.40,
                'amount_paid' => 7849901.40,
                'balance' => 1010.10,
                'status' => 'paid',
                'purpose' => 'personal',
                'guarantor' => null,
                'notes' => 'Normal Loan - Top Up',
            ],
            // Row 24
            [
                'loan_number' => 'LN024',
                'member_number' => 'FND3',
                'loan_product_id' => null,
                'principal_amount' => 8872764.10,
                'interest_rate' => 0.00,
                'term_months' => 19,
                'application_date' => '2024-03-26',
                'approval_date' => '2024-03-26',
                'disbursement_date' => '2024-03-26',
                'maturity_date' => '2025-10-26',
                'monthly_payment' => 361811.60,
                'total_amount_due' => 6874420.14,
                'amount_paid' => 6874420.14,
                'balance' => 0.38,
                'status' => 'paid',
                'purpose' => 'personal',
                'guarantor' => null,
                'notes' => 'Normal Loan - Top Up',
            ],
            // Row 25
            [
                'loan_number' => 'LN025',
                'member_number' => 'SCH13',
                'loan_product_id' => null,
                'principal_amount' => 1852020.20,
                'interest_rate' => 0.00,
                'term_months' => 36,
                'application_date' => '2023-04-26',
                'approval_date' => '2023-04-26',
                'disbursement_date' => '2023-04-26',
                'maturity_date' => '2026-03-26',
                'monthly_payment' => 51445.01,
                'total_amount_due' => 1852020.36,
                'amount_paid' => 1852020.36,
                'balance' => 10627.20,
                'status' => 'paid',
                'purpose' => 'education',
                'guarantor' => null,
                'notes' => 'Device Loan - New',
            ],
            // Row 26
            [
                'loan_number' => 'LN026',
                'member_number' => 'FND1',
                'loan_product_id' => null,
                'principal_amount' => 1547474.75,
                'interest_rate' => 0.00,
                'term_months' => 24,
                'application_date' => '2023-01-26',
                'approval_date' => '2023-01-26',
                'disbursement_date' => '2023-01-26',
                'maturity_date' => '2024-12-26',
                'monthly_payment' => 64478.11,
                'total_amount_due' => 1547474.64,
                'amount_paid' => 1547474.64,
                'balance' => 0.00,
                'status' => 'paid',
                'purpose' => 'education',
                'guarantor' => null,
                'notes' => 'Device Loan - New',
            ],
            // Row 27
            [
                'loan_number' => 'LN027',
                'member_number' => 'SCH2',
                'loan_product_id' => null,
                'principal_amount' => 2664899.20,
                'interest_rate' => 0.00,
                'term_months' => 33,
                'application_date' => '2023-09-26',
                'approval_date' => '2023-09-26',
                'disbursement_date' => '2023-09-26',
                'maturity_date' => '2026-05-26',
                'monthly_payment' => 74024.98,
                'total_amount_due' => 2440576.34,
                'amount_paid' => 2440576.34,
                'balance' => 0.25,
                'status' => 'paid',
                'purpose' => 'education',
                'guarantor' => null,
                'notes' => 'Device Loan - New',
            ],
            // Row 28
            [
                'loan_number' => 'LN028',
                'member_number' => 'PRM1',
                'loan_product_id' => null,
                'principal_amount' => 3540707.03,
                'interest_rate' => 0.00,
                'term_months' => 5,
                'application_date' => '2024-01-26',
                'approval_date' => '2024-01-26',
                'disbursement_date' => '2024-01-26',
                'maturity_date' => '2024-06-26',
                'monthly_payment' => 306861.28,
                'total_amount_due' => 1534306.40,
                'amount_paid' => 1534306.40,
                'balance' => 303.03,
                'status' => 'paid',
                'purpose' => 'emergency',
                'guarantor' => null,
                'notes' => 'Emmergence Loan - New',
            ],
            // Row 29
            [
                'loan_number' => 'LN029',
                'member_number' => 'ORD5',
                'loan_product_id' => null,
                'principal_amount' => 2025556.03,
                'interest_rate' => 0.00,
                'term_months' => 5,
                'application_date' => '2024-04-26',
                'approval_date' => '2024-04-26',
                'disbursement_date' => '2024-04-26',
                'maturity_date' => '2024-09-26',
                'monthly_payment' => 445622.33,
                'total_amount_due' => 2228111.65,
                'amount_paid' => 2228111.65,
                'balance' => 303.03,
                'status' => 'paid',
                'purpose' => 'emergency',
                'guarantor' => null,
                'notes' => 'Emmergence Loan - New',
            ],
            // Row 30
            [
                'loan_number' => 'LN030',
                'member_number' => 'ASC9',
                'loan_product_id' => null,
                'principal_amount' => 1625303.03,
                'interest_rate' => 0.00,
                'term_months' => 12,
                'application_date' => '2022-12-26',
                'approval_date' => '2022-12-26',
                'disbursement_date' => '2022-12-26',
                'maturity_date' => '2023-11-26',
                'monthly_payment' => 167947.98,
                'total_amount_due' => 2015375.76,
                'amount_paid' => 2015375.76,
                'balance' => 303.03,
                'status' => 'paid',
                'purpose' => 'emergency',
                'guarantor' => null,
                'notes' => 'Emmergence Loan - New',
            ],
            // Row 31
            [
                'loan_number' => 'LN031',
                'member_number' => 'ASC18',
                'loan_product_id' => null,
                'principal_amount' => 863636.36,
                'interest_rate' => 0.00,
                'term_months' => 36,
                'application_date' => '2022-10-26',
                'approval_date' => '2022-10-26',
                'disbursement_date' => '2022-10-26',
                'maturity_date' => '2025-09-26',
                'monthly_payment' => 67171.72,
                'total_amount_due' => 2418181.92,
                'amount_paid' => 2418181.92,
                'balance' => 8636.36,
                'status' => 'paid',
                'purpose' => 'personal',
                'guarantor' => null,
                'notes' => 'Quick loan - Restructured',
            ],
            // Row 32
            [
                'loan_number' => 'LN032',
                'member_number' => 'ASC7',
                'loan_product_id' => null,
                'principal_amount' => 228451.52,
                'interest_rate' => 0.00,
                'term_months' => 96,
                'application_date' => '2022-07-26',
                'approval_date' => '2022-07-26',
                'disbursement_date' => '2022-07-26',
                'maturity_date' => '2030-06-26',
                'monthly_payment' => 13802.28,
                'total_amount_due' => 1325033.88,
                'amount_paid' => 1325033.88,
                'balance' => 155006.89,
                'status' => 'active',
                'purpose' => 'personal',
                'guarantor' => null,
                'notes' => 'Quick loan - New - Deduct Savings',
            ],
            // Row 33
            [
                'loan_number' => 'LN033',
                'member_number' => 'ASC2',
                'loan_product_id' => null,
                'principal_amount' => 1151010.10,
                'interest_rate' => 0.00,
                'term_months' => 12,
                'application_date' => '2023-05-26',
                'approval_date' => '2023-05-26',
                'disbursement_date' => '2023-05-26',
                'maturity_date' => '2024-04-26',
                'monthly_payment' => 153468.01,
                'total_amount_due' => 1841616.12,
                'amount_paid' => 1841616.12,
                'balance' => 1010.10,
                'status' => 'paid',
                'purpose' => 'personal',
                'guarantor' => null,
                'notes' => 'Quick loan - New',
            ],
            // Row 34
            [
                'loan_number' => 'LN034',
                'member_number' => 'ASC2',
                'loan_product_id' => null,
                'principal_amount' => 1834343.43,
                'interest_rate' => 0.00,
                'term_months' => 12,
                'application_date' => '2023-07-26',
                'approval_date' => '2023-07-26',
                'disbursement_date' => '2023-07-26',
                'maturity_date' => '2024-06-26',
                'monthly_payment' => 244579.12,
                'total_amount_due' => 2934949.44,
                'amount_paid' => 2934949.44,
                'balance' => 1010.10,
                'status' => 'paid',
                'purpose' => 'personal',
                'guarantor' => null,
                'notes' => 'Quick loan - New',
            ],
            // Row 35
            [
                'loan_number' => 'LN035',
                'member_number' => 'ASC81',
                'loan_product_id' => null,
                'principal_amount' => 3068686.87,
                'interest_rate' => 0.00,
                'term_months' => 36,
                'application_date' => '2023-08-26',
                'approval_date' => '2023-08-26',
                'disbursement_date' => '2023-08-26',
                'maturity_date' => '2026-07-26',
                'monthly_payment' => 140477.67,
                'total_amount_due' => 5057196.12,
                'amount_paid' => 5057196.12,
                'balance' => 992893.23,
                'status' => 'active',
                'purpose' => 'business',
                'guarantor' => null,
                'notes' => 'Business Loan - New - Deduct Savings',
            ],
            // Row 36
            [
                'loan_number' => 'LN036',
                'member_number' => 'BA2',
                'loan_product_id' => null,
                'principal_amount' => 5088888.89,
                'interest_rate' => 0.00,
                'term_months' => 24,
                'application_date' => '2023-08-26',
                'approval_date' => '2023-08-26',
                'disbursement_date' => '2023-08-26',
                'maturity_date' => '2025-07-26',
                'monthly_payment' => 303637.04,
                'total_amount_due' => 7287288.96,
                'amount_paid' => 7287288.96,
                'balance' => 0.00,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => null,
                'notes' => 'Business Loan - New',
            ],
            // Row 37
            [
                'loan_number' => 'LN037',
                'member_number' => 'BA1',
                'loan_product_id' => null,
                'principal_amount' => 5088888.89,
                'interest_rate' => 0.00,
                'term_months' => 24,
                'application_date' => '2023-08-26',
                'approval_date' => '2023-08-26',
                'disbursement_date' => '2023-08-26',
                'maturity_date' => '2025-07-26',
                'monthly_payment' => 303637.04,
                'total_amount_due' => 7287288.96,
                'amount_paid' => 7287288.96,
                'balance' => 3834951.20,
                'status' => 'active',
                'purpose' => 'business',
                'guarantor' => null,
                'notes' => 'Business Loan - New - Deduct Savings',
            ],
            // Row 38
            [
                'loan_number' => 'LN038',
                'member_number' => 'ASC108',
                'loan_product_id' => null,
                'principal_amount' => 3887984.85,
                'interest_rate' => 0.00,
                'term_months' => 22,
                'application_date' => '2023-08-26',
                'approval_date' => '2023-08-26',
                'disbursement_date' => '2023-08-26',
                'maturity_date' => '2025-06-26',
                'monthly_payment' => 231983.10,
                'total_amount_due' => 5103628.20,
                'amount_paid' => 2319831.00,
                'balance' => 2783797.20,
                'status' => 'active',
                'purpose' => 'business',
                'guarantor' => null,
                'notes' => 'Business Loan - New',
            ],
            // Row 39
            [
                'loan_number' => 'LN039',
                'member_number' => 'ASC61',
                'loan_product_id' => null,
                'principal_amount' => 3887984.85,
                'interest_rate' => 0.00,
                'term_months' => 22,
                'application_date' => '2023-08-26',
                'approval_date' => '2023-08-26',
                'disbursement_date' => '2023-08-26',
                'maturity_date' => '2025-06-26',
                'monthly_payment' => 231983.10,
                'total_amount_due' => 5104592.20,
                'amount_paid' => 5104592.20,
                'balance' => 8080.81,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => null,
                'notes' => 'Business Loan - New',
            ],
            // Row 40
            [
                'loan_number' => 'LN040',
                'member_number' => 'ASC61',
                'loan_product_id' => null,
                'principal_amount' => 935168.01,
                'interest_rate' => 0.00,
                'term_months' => 15,
                'application_date' => '2024-03-26',
                'approval_date' => '2024-03-26',
                'disbursement_date' => '2024-03-26',
                'maturity_date' => '2025-06-26',
                'monthly_payment' => 55798.36,
                'total_amount_due' => 836975.40,
                'amount_paid' => 836975.40,
                'balance' => 9351.68,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => null,
                'notes' => 'Business Loan - Restructured',
            ],
            // Row 41
            [
                'loan_number' => 'LN041',
                'member_number' => 'ASC1',
                'loan_product_id' => null,
                'principal_amount' => 1314642.42,
                'interest_rate' => 0.00,
                'term_months' => 24,
                'application_date' => '2021-12-26',
                'approval_date' => '2021-12-26',
                'disbursement_date' => '2021-12-26',
                'maturity_date' => '2023-11-26',
                'monthly_payment' => 61349.98,
                'total_amount_due' => 1472399.52,
                'amount_paid' => 1472399.52,
                'balance' => 23146.42,
                'status' => 'active',
                'purpose' => 'personal',
                'guarantor' => null,
                'notes' => 'Bond loan - New - Continue Follow Up',
            ],
            // Row 42
            [
                'loan_number' => 'LN042',
                'member_number' => 'ASC7',
                'loan_product_id' => null,
                'principal_amount' => 2861952.53,
                'interest_rate' => 0.00,
                'term_months' => 96,
                'application_date' => '2022-07-26',
                'approval_date' => '2022-07-26',
                'disbursement_date' => '2022-07-26',
                'maturity_date' => '2030-06-26',
                'monthly_payment' => 69593.15,
                'total_amount_due' => 6680922.40,
                'amount_paid' => 6680922.40,
                'balance' => 1840724.09,
                'status' => 'active',
                'purpose' => 'business',
                'guarantor' => 'Erick Buberwa',
                'notes' => 'Guaranteed Loan - Restructured - Deduct Savings',
            ],
            // Row 43
            [
                'loan_number' => 'LN043',
                'member_number' => 'ASC4',
                'loan_product_id' => null,
                'principal_amount' => 2216073.74,
                'interest_rate' => 0.00,
                'term_months' => 96,
                'application_date' => '2022-07-26',
                'approval_date' => '2022-07-26',
                'disbursement_date' => '2022-07-26',
                'maturity_date' => '2030-06-26',
                'monthly_payment' => 53887.53,
                'total_amount_due' => 5173253.88,
                'amount_paid' => 5173253.88,
                'balance' => 1137233.08,
                'status' => 'active',
                'purpose' => 'business',
                'guarantor' => 'Erick Buberwa',
                'notes' => 'Guaranteed Loan - Restructured - Continue Follow Up',
            ],
            // Row 44
            [
                'loan_number' => 'LN044',
                'member_number' => 'ASC21',
                'loan_product_id' => null,
                'principal_amount' => 2053020.20,
                'interest_rate' => 0.00,
                'term_months' => 18,
                'application_date' => '2022-03-26',
                'approval_date' => '2022-03-26',
                'disbursement_date' => '2022-03-26',
                'maturity_date' => '2023-08-26',
                'monthly_payment' => 141567.15,
                'total_amount_due' => 2548208.72,
                'amount_paid' => 2548208.72,
                'balance' => 2020.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Emmanuel Elioth Lulandala',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 45
            [
                'loan_number' => 'LN045',
                'member_number' => 'ASC18',
                'loan_product_id' => null,
                'principal_amount' => 2680394.95,
                'interest_rate' => 0.00,
                'term_months' => 27,
                'application_date' => '2022-04-26',
                'approval_date' => '2022-04-26',
                'disbursement_date' => '2022-04-26',
                'maturity_date' => '2024-07-26',
                'monthly_payment' => 136531.38,
                'total_amount_due' => 3686347.12,
                'amount_paid' => 3686347.12,
                'balance' => 2020.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Kelvin M. Mwita',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 46
            [
                'loan_number' => 'LN046',
                'member_number' => 'ASC29',
                'loan_product_id' => null,
                'principal_amount' => 4082020.20,
                'interest_rate' => 0.00,
                'term_months' => 36,
                'application_date' => '2022-04-26',
                'approval_date' => '2022-04-26',
                'disbursement_date' => '2022-04-26',
                'maturity_date' => '2025-03-26',
                'monthly_payment' => 168088.52,
                'total_amount_due' => 6051186.72,
                'amount_paid' => 6051186.72,
                'balance' => 2020.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Mary Mwinuka',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 46
            [
                'loan_number' => 'LN047',
                'member_number' => 'ASC31',
                'loan_product_id' => null,
                'principal_amount' => 8114020.20,
                'interest_rate' => 0.00,
                'term_months' => 24,
                'application_date' => '2022-04-26',
                'approval_date' => '2022-04-26',
                'disbursement_date' => '2022-04-26',
                'maturity_date' => '2024-03-26',
                'monthly_payment' => 446812.05,
                'total_amount_due' => 10723489.16,
                'amount_paid' => 10723489.16,
                'balance' => 2020.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Christina Maeda',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 47
            [
                'loan_number' => 'LN048',
                'member_number' => 'ASC11',
                'loan_product_id' => null,
                'principal_amount' => 1402020.20,
                'interest_rate' => 0.00,
                'term_months' => 17,
                'application_date' => '2022-07-26',
                'approval_date' => '2022-07-26',
                'disbursement_date' => '2022-07-26',
                'maturity_date' => '2023-12-26',
                'monthly_payment' => 101959.86,
                'total_amount_due' => 1733317.62,
                'amount_paid' => 1733317.62,
                'balance' => 2020.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Cuthbert William',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 48
            [
                'loan_number' => 'LN049',
                'member_number' => 'ASC21',
                'loan_product_id' => null,
                'principal_amount' => 2352272.73,
                'interest_rate' => 0.00,
                'term_months' => 114,
                'application_date' => '2023-07-26',
                'approval_date' => '2023-07-26',
                'disbursement_date' => '2023-07-26',
                'maturity_date' => '2032-12-26',
                'monthly_payment' => 20454.55,
                'total_amount_due' => 2331914.26,
                'amount_paid' => 2331914.26,
                'balance' => 2019714.26,
                'status' => 'active',
                'purpose' => 'education',
                'guarantor' => null,
                'notes' => 'Device Loan - Restructured - Deduct Savings',
            ],
            // Row 49
            [
                'loan_number' => 'LN050',
                'member_number' => 'PRM2',
                'loan_product_id' => null,
                'principal_amount' => 2352272.73,
                'interest_rate' => 0.00,
                'term_months' => 36,
                'application_date' => '2023-07-26',
                'approval_date' => '2023-07-26',
                'disbursement_date' => '2023-07-26',
                'maturity_date' => '2026-06-26',
                'monthly_payment' => 20454.55,
                'total_amount_due' => 736363.48,
                'amount_paid' => 736363.48,
                'balance' => 0.00,
                'status' => 'paid',
                'purpose' => 'education',
                'guarantor' => null,
                'notes' => 'Device Loan - Restructured',
            ],
            // Row 50
            [
                'loan_number' => 'LN051',
                'member_number' => 'ASC39',
                'loan_product_id' => null,
                'principal_amount' => 5092020.20,
                'interest_rate' => 0.00,
                'term_months' => 24,
                'application_date' => '2022-07-26',
                'approval_date' => '2022-07-26',
                'disbursement_date' => '2022-07-26',
                'maturity_date' => '2024-06-26',
                'monthly_payment' => 282946.59,
                'total_amount_due' => 6790718.16,
                'amount_paid' => 6790718.16,
                'balance' => 2020.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Bakari A. Semvua',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 51
            [
                'loan_number' => 'LN052',
                'member_number' => 'ASC32',
                'loan_product_id' => null,
                'principal_amount' => 7412205.05,
                'interest_rate' => 0.00,
                'term_months' => 16,
                'application_date' => '2023-04-26',
                'approval_date' => '2023-04-26',
                'disbursement_date' => '2023-04-26',
                'maturity_date' => '2024-07-26',
                'monthly_payment' => 201859.05,
                'total_amount_due' => 3229744.80,
                'amount_paid' => 3229744.80,
                'balance' => 74122.05,
                'status' => 'active',
                'purpose' => 'business',
                'guarantor' => 'Mkula Beateice Machumu',
                'notes' => 'Guaranteed Loan - Restructured - Continue Follow Up',
            ],
            // Row 52
            [
                'loan_number' => 'LN053',
                'member_number' => 'ASC44',
                'loan_product_id' => null,
                'principal_amount' => 5002019.19,
                'interest_rate' => 0.00,
                'term_months' => 24,
                'application_date' => '2022-08-26',
                'approval_date' => '2022-08-26',
                'disbursement_date' => '2022-08-26',
                'maturity_date' => '2024-07-26',
                'monthly_payment' => 277945.53,
                'total_amount_due' => 6670692.72,
                'amount_paid' => 6670692.72,
                'balance' => 2020.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Caesar Maulaga',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 53
            [
                'loan_number' => 'LN054',
                'member_number' => 'ASC20',
                'loan_product_id' => null,
                'principal_amount' => 1043020.20,
                'interest_rate' => 0.00,
                'term_months' => 24,
                'application_date' => '2022-09-26',
                'approval_date' => '2022-09-26',
                'disbursement_date' => '2022-09-26',
                'maturity_date' => '2024-08-26',
                'monthly_payment' => 57957.16,
                'total_amount_due' => 1390971.68,
                'amount_paid' => 1390971.68,
                'balance' => 2020.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Mary Mwinuka',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 54
            [
                'loan_number' => 'LN055',
                'member_number' => null,
                'loan_product_id' => null,
                'principal_amount' => 5122020.20,
                'interest_rate' => 0.00,
                'term_months' => 17,
                'application_date' => '2022-10-26',
                'approval_date' => '2022-10-26',
                'disbursement_date' => '2022-10-26',
                'maturity_date' => '2024-02-26',
                'monthly_payment' => 284613.59,
                'total_amount_due' => 4836517.32,
                'amount_paid' => 4836517.32,
                'balance' => 0.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Emmanuel Elioth Lulandala',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 55
            [
                'loan_number' => 'LN056',
                'member_number' => 'ORD6',
                'loan_product_id' => null,
                'principal_amount' => 5083020.20,
                'interest_rate' => 0.00,
                'term_months' => 24,
                'application_date' => '2022-10-26',
                'approval_date' => '2022-10-26',
                'disbursement_date' => '2022-10-26',
                'maturity_date' => '2024-09-26',
                'monthly_payment' => 282446.49,
                'total_amount_due' => 6778715.68,
                'amount_paid' => 6778715.68,
                'balance' => 2020.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Erick Buberwa',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 56
            [
                'loan_number' => 'LN057',
                'member_number' => 'ASC56',
                'loan_product_id' => null,
                'principal_amount' => 3062630.30,
                'interest_rate' => 0.00,
                'term_months' => 21,
                'application_date' => '2022-11-26',
                'approval_date' => '2022-11-26',
                'disbursement_date' => '2022-11-26',
                'maturity_date' => '2024-08-26',
                'monthly_payment' => 188410.10,
                'total_amount_due' => 3956612.10,
                'amount_paid' => 3956612.10,
                'balance' => 2020.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Emmanuel Elioth Lulandala',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 57
            [
                'loan_number' => 'LN058',
                'member_number' => 'ASC70',
                'loan_product_id' => null,
                'principal_amount' => 2562020.20,
                'interest_rate' => 0.00,
                'term_months' => 24,
                'application_date' => '2023-02-26',
                'approval_date' => '2023-02-26',
                'disbursement_date' => '2023-02-26',
                'maturity_date' => '2025-01-26',
                'monthly_payment' => 142362.92,
                'total_amount_due' => 3416710.08,
                'amount_paid' => 3416710.08,
                'balance' => 2020.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Emmanuel Elioth Lulandala',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 58
            [
                'loan_number' => 'LN059',
                'member_number' => 'ASC60',
                'loan_product_id' => null,
                'principal_amount' => 2057020.20,
                'interest_rate' => 0.00,
                'term_months' => 24,
                'application_date' => '2023-02-26',
                'approval_date' => '2023-02-26',
                'disbursement_date' => '2023-02-26',
                'maturity_date' => '2025-01-26',
                'monthly_payment' => 114301.76,
                'total_amount_due' => 2743242.24,
                'amount_paid' => 2743242.24,
                'balance' => 428511.94,
                'status' => 'active',
                'purpose' => 'business',
                'guarantor' => 'Mary Mwinuka',
                'notes' => 'Guaranteed Loan - New - Deduct Savings',
            ],
            // Row 59
            [
                'loan_number' => 'LN060',
                'member_number' => 'ASC65',
                'loan_product_id' => null,
                'principal_amount' => 4463314.14,
                'interest_rate' => 0.00,
                'term_months' => 36,
                'application_date' => '2024-03-26',
                'approval_date' => '2024-03-26',
                'disbursement_date' => '2024-03-26',
                'maturity_date' => '2027-02-26',
                'monthly_payment' => 186021.01,
                'total_amount_due' => 6696756.36,
                'amount_paid' => 6696756.36,
                'balance' => 1727722.54,
                'status' => 'active',
                'purpose' => 'business',
                'guarantor' => 'Mary Mwinuka',
                'notes' => 'Guaranteed Loan - New - Deduct Savings',
            ],
            // Row 60
            [
                'loan_number' => 'LN061',
                'member_number' => 'ASC12',
                'loan_product_id' => null,
                'principal_amount' => 10142020.20,
                'interest_rate' => 0.00,
                'term_months' => 20,
                'application_date' => '2023-02-26',
                'approval_date' => '2023-02-26',
                'disbursement_date' => '2023-02-26',
                'maturity_date' => '2024-10-26',
                'monthly_payment' => 563558.26,
                'total_amount_due' => 11271614.20,
                'amount_paid' => 11271614.20,
                'balance' => 2020.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Kanti Ambrose Kimario',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 61
            [
                'loan_number' => 'LN062',
                'member_number' => 'ASC62',
                'loan_product_id' => null,
                'principal_amount' => 1043020.20,
                'interest_rate' => 0.00,
                'term_months' => 24,
                'application_date' => '2023-01-26',
                'approval_date' => '2023-01-26',
                'disbursement_date' => '2023-01-26',
                'maturity_date' => '2024-12-26',
                'monthly_payment' => 57957.16,
                'total_amount_due' => 1390971.68,
                'amount_paid' => 1390971.68,
                'balance' => 2020.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Victoria S.Mwambungu',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 62
            [
                'loan_number' => 'LN063',
                'member_number' => 'ASC37',
                'loan_product_id' => null,
                'principal_amount' => 5612020.20,
                'interest_rate' => 0.00,
                'term_months' => 24,
                'application_date' => '2023-02-26',
                'approval_date' => '2023-02-26',
                'disbursement_date' => '2023-02-26',
                'maturity_date' => '2025-01-26',
                'monthly_payment' => 311841.26,
                'total_amount_due' => 7484190.24,
                'amount_paid' => 7484190.24,
                'balance' => 2020.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Kanti Ambrose Kimario',
                'notes' => 'Guaranteed Loan - Top Up',
            ],
            // Row 63
            [
                'loan_number' => 'LN064',
                'member_number' => 'ASC63',
                'loan_product_id' => null,
                'principal_amount' => 2557575.76,
                'interest_rate' => 0.00,
                'term_months' => 21,
                'application_date' => '2023-12-26',
                'approval_date' => '2023-12-26',
                'disbursement_date' => '2023-12-26',
                'maturity_date' => '2025-09-26',
                'monthly_payment' => 142115.96,
                'total_amount_due' => 2984772.52,
                'amount_paid' => 2984772.52,
                'balance' => 2020.65,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Kanti Ambrose Kimario',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 64
            [
                'loan_number' => 'LN065',
                'member_number' => 'ASC55',
                'loan_product_id' => null,
                'principal_amount' => 3072020.20,
                'interest_rate' => 0.00,
                'term_months' => 24,
                'application_date' => '2023-05-26',
                'approval_date' => '2023-05-26',
                'disbursement_date' => '2023-05-26',
                'maturity_date' => '2025-04-26',
                'monthly_payment' => 170701.92,
                'total_amount_due' => 4096846.08,
                'amount_paid' => 4096846.08,
                'balance' => 2020.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Emmanuel Elioth Lulandala',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 65
            [
                'loan_number' => 'LN066',
                'member_number' => 'ASC16',
                'loan_product_id' => null,
                'principal_amount' => 2257020.20,
                'interest_rate' => 0.00,
                'term_months' => 24,
                'application_date' => '2023-05-26',
                'approval_date' => '2023-05-26',
                'disbursement_date' => '2023-05-26',
                'maturity_date' => '2025-04-26',
                'monthly_payment' => 125415.09,
                'total_amount_due' => 3009962.16,
                'amount_paid' => 3009962.16,
                'balance' => 2020.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Emmanuel Elioth Lulandala',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 66
            [
                'loan_number' => 'LN067',
                'member_number' => 'ASC76',
                'loan_product_id' => null,
                'principal_amount' => 2567020.20,
                'interest_rate' => 0.00,
                'term_months' => 21,
                'application_date' => '2023-06-26',
                'approval_date' => '2023-06-26',
                'disbursement_date' => '2023-06-26',
                'maturity_date' => '2025-03-26',
                'monthly_payment' => 142640.76,
                'total_amount_due' => 2995792.64,
                'amount_paid' => 2995792.64,
                'balance' => 2020.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Mary Mwinuka',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 67
            [
                'loan_number' => 'LN068',
                'member_number' => 'ASC47',
                'loan_product_id' => null,
                'principal_amount' => 2337020.20,
                'interest_rate' => 0.00,
                'term_months' => 24,
                'application_date' => '2023-06-26',
                'approval_date' => '2023-06-26',
                'disbursement_date' => '2023-06-26',
                'maturity_date' => '2025-05-26',
                'monthly_payment' => 129860.42,
                'total_amount_due' => 3116650.08,
                'amount_paid' => 3116650.08,
                'balance' => 2020.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Mary Mwinuka',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 68
            [
                'loan_number' => 'LN069',
                'member_number' => 'ASC24',
                'loan_product_id' => null,
                'principal_amount' => 8652020.20,
                'interest_rate' => 0.00,
                'term_months' => 24,
                'application_date' => '2023-07-26',
                'approval_date' => '2023-07-26',
                'disbursement_date' => '2023-07-26',
                'maturity_date' => '2025-06-26',
                'monthly_payment' => 480763.92,
                'total_amount_due' => 11538334.08,
                'amount_paid' => 11538334.08,
                'balance' => 0.00,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Mary Mwinuka',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 69
            [
                'loan_number' => 'LN070',
                'member_number' => 'ASC77',
                'loan_product_id' => null,
                'principal_amount' => 1042424.24,
                'interest_rate' => 0.00,
                'term_months' => 20,
                'application_date' => '2023-08-26',
                'approval_date' => '2023-08-26',
                'disbursement_date' => '2023-08-26',
                'maturity_date' => '2025-03-26',
                'monthly_payment' => 57924.04,
                'total_amount_due' => 1158480.80,
                'amount_paid' => 1158480.80,
                'balance' => 24202.70,
                'status' => 'active',
                'purpose' => 'business',
                'guarantor' => 'Mary Mwinuka',
                'notes' => 'Guaranteed Loan - New - Continue Follow Up',
            ],
            // Row 70
            [
                'loan_number' => 'LN071',
                'member_number' => 'ASC41',
                'loan_product_id' => null,
                'principal_amount' => 4020989.90,
                'interest_rate' => 0.00,
                'term_months' => 31,
                'application_date' => '2023-08-26',
                'approval_date' => '2023-08-26',
                'disbursement_date' => '2023-08-26',
                'maturity_date' => '2026-02-26',
                'monthly_payment' => 153964.68,
                'total_amount_due' => 4772904.80,
                'amount_paid' => 4772904.80,
                'balance' => -0.19,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Emmanuel Elioth Lulandala',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 71
            [
                'loan_number' => 'LN072',
                'member_number' => 'ASC82',
                'loan_product_id' => null,
                'principal_amount' => 2052525.25,
                'interest_rate' => 0.00,
                'term_months' => 24,
                'application_date' => '2023-08-26',
                'approval_date' => '2023-08-26',
                'disbursement_date' => '2023-08-26',
                'maturity_date' => '2025-07-26',
                'monthly_payment' => 114051.99,
                'total_amount_due' => 2737247.68,
                'amount_paid' => 2737247.68,
                'balance' => 0.00,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'William Kaberege',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 72
            [
                'loan_number' => 'LN073',
                'member_number' => 'ASC3',
                'loan_product_id' => null,
                'principal_amount' => 4620226.26,
                'interest_rate' => 0.00,
                'term_months' => 24,
                'application_date' => '2023-08-26',
                'approval_date' => '2023-08-26',
                'disbursement_date' => '2023-08-26',
                'maturity_date' => '2025-07-26',
                'monthly_payment' => 256730.57,
                'total_amount_due' => 6161533.68,
                'amount_paid' => 6161533.68,
                'balance' => 0.00,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Kelvin M. Mwita',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 73
            [
                'loan_number' => 'LN074',
                'member_number' => null,
                'loan_product_id' => null,
                'principal_amount' => 3207381.82,
                'interest_rate' => 0.00,
                'term_months' => 14,
                'application_date' => '2023-08-26',
                'approval_date' => '2023-08-26',
                'disbursement_date' => '2023-08-26',
                'maturity_date' => '2024-09-26',
                'monthly_payment' => 273681.31,
                'total_amount_due' => 3829125.34,
                'amount_paid' => 3829125.34,
                'balance' => 0.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Caesar Maulaga',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 74
            [
                'loan_number' => 'LN075',
                'member_number' => 'ASC25',
                'loan_product_id' => null,
                'principal_amount' => 3567676.77,
                'interest_rate' => 0.00,
                'term_months' => 24,
                'application_date' => '2023-10-26',
                'approval_date' => '2023-10-26',
                'disbursement_date' => '2023-10-26',
                'maturity_date' => '2025-09-26',
                'monthly_payment' => 198243.91,
                'total_amount_due' => 4757853.84,
                'amount_paid' => 4757853.84,
                'balance' => -0.00,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Christina Maeda',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 75
            [
                'loan_number' => 'LN076',
                'member_number' => 'ASC51',
                'loan_product_id' => null,
                'principal_amount' => 3567676.77,
                'interest_rate' => 0.00,
                'term_months' => 24,
                'application_date' => '2023-09-26',
                'approval_date' => '2023-09-26',
                'disbursement_date' => '2023-09-26',
                'maturity_date' => '2025-08-26',
                'monthly_payment' => 198243.91,
                'total_amount_due' => 4757853.84,
                'amount_paid' => 4757853.84,
                'balance' => 0.00,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Mary Mwinuka',
                'notes' => 'Guaranteed Loan - Top Up',
            ],
            // Row 76
            [
                'loan_number' => 'LN077',
                'member_number' => 'ASC79',
                'loan_product_id' => null,
                'principal_amount' => 1042424.24,
                'interest_rate' => 0.00,
                'term_months' => 17,
                'application_date' => '2023-09-26',
                'approval_date' => '2023-09-26',
                'disbursement_date' => '2023-09-26',
                'maturity_date' => '2025-02-26',
                'monthly_payment' => 57924.04,
                'total_amount_due' => 985494.68,
                'amount_paid' => 985494.68,
                'balance' => 2020.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Victoria S.Mwambungu',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 77
            [
                'loan_number' => 'LN078',
                'member_number' => 'ASC40',
                'loan_product_id' => null,
                'principal_amount' => 3864340.40,
                'interest_rate' => 0.00,
                'term_months' => 12,
                'application_date' => '2023-09-26',
                'approval_date' => '2023-09-26',
                'disbursement_date' => '2023-09-26',
                'maturity_date' => '2024-08-26',
                'monthly_payment' => 375742.70,
                'total_amount_due' => 4508912.40,
                'amount_paid' => 4508912.40,
                'balance' => 2020.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Kelvin M. Mwita',
                'notes' => 'Guaranteed Loan - Top Up',
            ],
            // Row 78
            [
                'loan_number' => 'LN079',
                'member_number' => 'ASC23',
                'loan_product_id' => null,
                'principal_amount' => 6092929.29,
                'interest_rate' => 0.00,
                'term_months' => 9,
                'application_date' => '2023-10-26',
                'approval_date' => '2023-10-26',
                'disbursement_date' => '2023-10-26',
                'maturity_date' => '2024-07-26',
                'monthly_payment' => 253939.75,
                'total_amount_due' => 2285730.84,
                'amount_paid' => 2285730.84,
                'balance' => 2020.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Mary Mwinuka',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 79
            [
                'loan_number' => 'LN080',
                'member_number' => 'ASC84',
                'loan_product_id' => null,
                'principal_amount' => 5082828.28,
                'interest_rate' => 0.00,
                'term_months' => 24,
                'application_date' => '2023-11-26',
                'approval_date' => '2023-11-26',
                'disbursement_date' => '2023-11-26',
                'maturity_date' => '2025-10-26',
                'monthly_payment' => 282435.82,
                'total_amount_due' => 6778459.68,
                'amount_paid' => 6778459.68,
                'balance' => 0.00,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Mary Mwinuka',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 80
            [
                'loan_number' => 'LN081',
                'member_number' => 'ASC85',
                'loan_product_id' => null,
                'principal_amount' => 537373.74,
                'interest_rate' => 0.00,
                'term_months' => 12,
                'application_date' => '2023-11-26',
                'approval_date' => '2023-11-26',
                'disbursement_date' => '2023-11-26',
                'maturity_date' => '2024-10-26',
                'monthly_payment' => 52250.64,
                'total_amount_due' => 627007.68,
                'amount_paid' => 627007.68,
                'balance' => 2020.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Sarah Richard Mhagama',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 81
            [
                'loan_number' => 'LN082',
                'member_number' => 'ASC13',
                'loan_product_id' => null,
                'principal_amount' => 3693939.39,
                'interest_rate' => 0.00,
                'term_months' => 19,
                'application_date' => '2023-12-26',
                'approval_date' => '2023-12-26',
                'disbursement_date' => '2023-12-26',
                'maturity_date' => '2025-07-26',
                'monthly_payment' => 205259.90,
                'total_amount_due' => 3900498.80,
                'amount_paid' => 3900498.80,
                'balance' => 2020.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Emmanuel Elioth Lulandala',
                'notes' => 'Guaranteed Loan - Top Up',
            ],
            // Row 82
            [
                'loan_number' => 'LN083',
                'member_number' => 'ASC80',
                'loan_product_id' => null,
                'principal_amount' => 5082828.28,
                'interest_rate' => 0.00,
                'term_months' => 16,
                'application_date' => '2023-12-26',
                'approval_date' => '2023-12-26',
                'disbursement_date' => '2023-12-26',
                'maturity_date' => '2025-04-26',
                'monthly_payment' => 282435.82,
                'total_amount_due' => 4519870.52,
                'amount_paid' => 4519870.52,
                'balance' => 2020.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Mary Mwinuka',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 83
            [
                'loan_number' => 'LN084',
                'member_number' => 'ASC64',
                'loan_product_id' => null,
                'principal_amount' => 1886725.25,
                'interest_rate' => 0.00,
                'term_months' => 18,
                'application_date' => '2023-12-26',
                'approval_date' => '2023-12-26',
                'disbursement_date' => '2023-12-26',
                'maturity_date' => '2025-06-26',
                'monthly_payment' => 104839.03,
                'total_amount_due' => 1887775.16,
                'amount_paid' => 1887775.16,
                'balance' => 2020.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Caesar Maulaga',
                'notes' => 'Guaranteed Loan - Top Up',
            ],
            // Row 84
            [
                'loan_number' => 'LN085',
                'member_number' => 'ASC68',
                'loan_product_id' => null,
                'principal_amount' => 2052525.25,
                'interest_rate' => 0.00,
                'term_months' => 10,
                'application_date' => '2024-01-26',
                'approval_date' => '2024-01-26',
                'disbursement_date' => '2024-01-26',
                'maturity_date' => '2024-10-26',
                'monthly_payment' => 233782.63,
                'total_amount_due' => 2337826.28,
                'amount_paid' => 2337826.28,
                'balance' => 2020.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Victoria S.Mwambungu',
                'notes' => 'Guaranteed Loan - New',
            ],
            // Row 85
            [
                'loan_number' => 'LN086',
                'member_number' => 'ASC67',
                'loan_product_id' => null,
                'principal_amount' => 2897422.22,
                'interest_rate' => 0.00,
                'term_months' => 16,
                'application_date' => '2024-01-26',
                'approval_date' => '2024-01-26',
                'disbursement_date' => '2024-01-26',
                'maturity_date' => '2025-04-26',
                'monthly_payment' => 161000.09,
                'total_amount_due' => 2575701.44,
                'amount_paid' => 2575701.44,
                'balance' => 2020.28,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Mary Mwinuka',
                'notes' => 'Guaranteed Loan - Top Up',
            ],
            // Row 86
            [
                'loan_number' => 'LN087',
                'member_number' => 'ASC8',
                'loan_product_id' => null,
                'principal_amount' => 4060468.69,
                'interest_rate' => 0.00,
                'term_months' => 24,
                'application_date' => '2024-01-26',
                'approval_date' => '2024-01-26',
                'disbursement_date' => '2024-01-26',
                'maturity_date' => '2025-12-26',
                'monthly_payment' => 225626.71,
                'total_amount_due' => 5415041.04,
                'amount_paid' => 5415041.04,
                'balance' => 0.00,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Emmanuel Elioth Lulandala',
                'notes' => 'Guaranteed Loan - Top Up',
            ],
            // Row 87
            [
                'loan_number' => 'LN088',
                'member_number' => 'ASC50',
                'loan_product_id' => null,
                'principal_amount' => 7209711.11,
                'interest_rate' => 0.00,
                'term_months' => 18,
                'application_date' => '2023-10-26',
                'approval_date' => '2023-10-26',
                'disbursement_date' => '2023-10-26',
                'maturity_date' => '2025-04-26',
                'monthly_payment' => 300484.74,
                'total_amount_due' => 5410241.44,
                'amount_paid' => 5410241.44,
                'balance' => 2020.20,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Mary Mwinuka',
                'notes' => 'Guaranteed Loan - Top Up',
            ],
            // Row 88
            [
                'loan_number' => 'LN089',
                'member_number' => 'ASC86',
                'loan_product_id' => null,
                'principal_amount' => 2052525.25,
                'interest_rate' => 0.00,
                'term_months' => 24,
                'application_date' => '2024-01-26',
                'approval_date' => '2024-01-26',
                'disbursement_date' => '2024-01-26',
                'maturity_date' => '2025-12-26',
                'monthly_payment' => 114051.99,
                'total_amount_due' => 2737247.68,
                'amount_paid' => 2737247.68,
                'balance' => 0.00,
                'status' => 'paid',
                'purpose' => 'business',
                'guarantor' => 'Victoria S.Mwambungu',
                'notes' => 'Guaranteed Loan - New',
            ],
        ];

        foreach ($loansData as $loanData) {
            // Add user_id if member_number exists in the map
            if (isset($loanData['member_number']) && isset($memberToUserMap[$loanData['member_number']])) {
                $loanData['user_id'] = $memberToUserMap[$loanData['member_number']];
            }
            Loan::create($loanData);
        }

        // Re-enable foreign key constraints
        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        $this->command->info('Loan seeder completed successfully. ' . count($loansData) . ' loans seeded.');
    }
}
