<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SavingPlanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key constraints
        DB::statement('SET FOREIGN_KEY_CHECKS=0');

        // Clear existing saving plans
        DB::table('saving_plans')->truncate();

        $savingPlansData = [
            [
                'name' => 'Abdala Saidi Abdala',
                'member_number' => 'SCH25',
                'membership' => 'Scholar',
                'periodic_amount' => 75000.00,
                'goal' => 900000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Abdulkarim Shabani Hussein',
                'member_number' => 'ASC116',
                'membership' => 'Associate',
                'periodic_amount' => 55556.00,
                'goal' => 500000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Abel Sokoni Simfukwe',
                'member_number' => 'ASC20',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 1200000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Agness Olomi',
                'member_number' => 'SCH37',
                'membership' => 'Scholar',
                'periodic_amount' => 104167.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'AIRINI ARNOLD JOHN',
                'member_number' => 'SCH4',
                'membership' => 'Scholar',
                'periodic_amount' => 20000.00,
                'goal' => 240000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Albert Sylvester Nkuhi',
                'member_number' => 'ASC1',
                'membership' => 'Associate',
                'periodic_amount' => 1250000.00,
                'goal' => 30000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'ALEXANDER ASHIR ASHIR',
                'member_number' => 'ASC79',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 6000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Anna Beda Kessy',
                'member_number' => 'ASC88',
                'membership' => 'Associate',
                'periodic_amount' => 166667.00,
                'goal' => 3000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Apendavyo Ramadhani',
                'member_number' => 'ASC31',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Arcard a.mshaijaki',
                'member_number' => 'ASC46',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Arkelaus Kailembo',
                'member_number' => 'ORD10',
                'membership' => 'Ordinary',
                'periodic_amount' => 125000.00,
                'goal' => 3000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Asha Mngazia',
                'member_number' => 'ASC32',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Aurelia Issack',
                'member_number' => 'ASC12',
                'membership' => 'Associate',
                'periodic_amount' => 833333.00,
                'goal' => 10000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Bahati Ramadhani Magoha',
                'member_number' => 'ASC40',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 1200000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Bakari A. Semvua',
                'member_number' => 'FND4',
                'membership' => 'Founder',
                'periodic_amount' => 120000.00,
                'goal' => 1440000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'BENSON MINJA',
                'member_number' => 'SCH38',
                'membership' => 'Scholar',
                'periodic_amount' => 20000.00,
                'goal' => 240000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'BONNY WILSON NGONDE',
                'member_number' => 'ASC43',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 2400000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Brighon E Urio',
                'member_number' => 'ASC67',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 15000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Caesar Maulaga',
                'member_number' => 'FND2',
                'membership' => 'Founder',
                'periodic_amount' => 222222.00,
                'goal' => 4000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Calist Paschal Chami',
                'member_number' => 'ASC19',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 1200000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Caroline Ceasar Shija',
                'member_number' => 'ASC75',
                'membership' => 'Associate',
                'periodic_amount' => 166667.00,
                'goal' => 10000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Catherine A. Kimario',
                'member_number' => 'ASC63',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 4800000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Chiku Edward',
                'member_number' => 'ASC57',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 1800000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Christina Maeda',
                'member_number' => 'ORD2',
                'membership' => 'Ordinary',
                'periodic_amount' => 300000.00,
                'goal' => 14400000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Christina Mgoji',
                'member_number' => 'ASC3',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Christopher Alex Msongore',
                'member_number' => 'ORD8',
                'membership' => 'Ordinary',
                'periodic_amount' => 120000.00,
                'goal' => 1440000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Cuthbert William',
                'member_number' => 'PRM3',
                'membership' => 'Promoter',
                'periodic_amount' => 277778.00,
                'goal' => 10000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Danford Mhagama',
                'member_number' => 'ASC29',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'DANIEL MATHIAS DANIEL',
                'member_number' => 'ASC27',
                'membership' => 'Associate',
                'periodic_amount' => 208333.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Daud Reuben Mwinuka',
                'member_number' => 'ASC47',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 1200000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Denis Epafra Munisi',
                'member_number' => 'ASC22',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Donica Fales John',
                'member_number' => 'SCH9',
                'membership' => 'Scholar',
                'periodic_amount' => 20000.00,
                'goal' => 240000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Lukombodzo E. Lulandala',
                'member_number' => 'ASC35',
                'membership' => 'Associate',
                'periodic_amount' => 833333.00,
                'goal' => 10000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Elinaja Samuel Mzava',
                'member_number' => 'ASC77',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 1200000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Elizabeth kisamu Charles',
                'member_number' => 'SCH30',
                'membership' => 'Scholar',
                'periodic_amount' => 138889.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Emmanuel Elioth Lulandala',
                'member_number' => 'PRM2',
                'membership' => 'Promoter',
                'periodic_amount' => 166667.00,
                'goal' => 10000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Emanuel P. Shayo',
                'member_number' => 'ASC55',
                'membership' => 'Associate',
                'periodic_amount' => 333333.00,
                'goal' => 4000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Enighenja Frank Mgonja',
                'member_number' => 'ASC82',
                'membership' => 'Associate',
                'periodic_amount' => 66667.00,
                'goal' => 2000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Enitha Msamba',
                'member_number' => 'ASC5',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Erasmus Urio',
                'member_number' => 'ASC61',
                'membership' => 'Associate',
                'periodic_amount' => 833333.00,
                'goal' => 10000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Erasto Gerald Luvanda',
                'member_number' => 'ASC8',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Erick Anselim Minde',
                'member_number' => 'ASC9',
                'membership' => 'Associate',
                'periodic_amount' => 69444.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Erick Buberwa',
                'member_number' => 'PRM5',
                'membership' => 'Promoter',
                'periodic_amount' => 120000.00,
                'goal' => 3600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Ester ezechiel Ndudumizi',
                'member_number' => 'ASC14',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Ester Mwinuka',
                'member_number' => 'ASC50',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Eufomia Pancras Mshanga',
                'member_number' => 'SCH7',
                'membership' => 'Scholar',
                'periodic_amount' => 20000.00,
                'goal' => 240000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Eva Lolusu',
                'member_number' => 'SCH31',
                'membership' => 'Scholar',
                'periodic_amount' => 20833.00,
                'goal' => 1000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Evod Materu',
                'member_number' => 'SCH8',
                'membership' => 'Scholar',
                'periodic_amount' => 83333.00,
                'goal' => 1000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Faraja David Kiwale',
                'member_number' => 'ASC60',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 1200000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Faustina festo Buberwa',
                'member_number' => 'ASC85',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Gloria Msemwa',
                'member_number' => 'ASC69',
                'membership' => 'Associate',
                'periodic_amount' => 291667.00,
                'goal' => 7000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Gloria Silvester Ndosi',
                'member_number' => 'ASC36',
                'membership' => 'Associate',
                'periodic_amount' => 416667.00,
                'goal' => 10000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Glory Kasanga',
                'member_number' => 'ASC71',
                'membership' => 'Associate',
                'periodic_amount' => 138889.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Golden Jeroboam Swai',
                'member_number' => 'SCH20',
                'membership' => 'Scholar',
                'periodic_amount' => 20000.00,
                'goal' => 240000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Goodluck Msack',
                'member_number' => 'ASC16',
                'membership' => 'Associate',
                'periodic_amount' => 9000000.00,
                'goal' => 108000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Hamisi Amiri Hasani',
                'member_number' => 'ASC11',
                'membership' => 'Associate',
                'periodic_amount' => 1000000.00,
                'goal' => 12000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Happiness Mzobora',
                'member_number' => 'ASC18',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Hekima S Mwasile',
                'member_number' => 'ASC120',
                'membership' => 'Associate',
                'periodic_amount' => 333333.00,
                'goal' => 2000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Hussein Hassan Laizer',
                'member_number' => 'ORD9',
                'membership' => 'Ordinary',
                'periodic_amount' => 120000.00,
                'goal' => 1440000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Innocence Babu Mainga',
                'member_number' => 'ASC81',
                'membership' => 'Associate',
                'periodic_amount' => 416667.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Irene Heaven',
                'member_number' => 'ASC87',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 7200000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Isack Samwel Mwekwa',
                'member_number' => 'ASC62',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Jackline Manase',
                'member_number' => 'SCH17',
                'membership' => 'Scholar',
                'periodic_amount' => 20000.00,
                'goal' => 240000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'James C. Magesa',
                'member_number' => 'ASC73',
                'membership' => 'Associate',
                'periodic_amount' => 416667.00,
                'goal' => 10000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'JANESTER HARSON',
                'member_number' => 'BA1',
                'membership' => 'Business Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Japhet Methusela Mgema',
                'member_number' => 'FND7',
                'membership' => 'Founder',
                'periodic_amount' => 416667.00,
                'goal' => 10000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Jesca G. Nyaki',
                'member_number' => 'ASC26',
                'membership' => 'Associate',
                'periodic_amount' => 833333.00,
                'goal' => 10000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Jesca michael cran',
                'member_number' => 'ASC74',
                'membership' => 'Associate',
                'periodic_amount' => 208333.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'John Siegfred Magalayashilinde',
                'member_number' => 'FND6',
                'membership' => 'Founder',
                'periodic_amount' => 120000.00,
                'goal' => 1440000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Joseph Charles Rukamya',
                'member_number' => 'ASC59',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Joseph zephania Musendo',
                'member_number' => 'SCH5',
                'membership' => 'Scholar',
                'periodic_amount' => 20000.00,
                'goal' => 480000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Josephine Anthony Massawe',
                'member_number' => 'ASC10',
                'membership' => 'Associate',
                'periodic_amount' => 520833.00,
                'goal' => 12500000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Josephine Kiwelu',
                'member_number' => 'ASC122',
                'membership' => 'Associate',
                'periodic_amount' => 80000.00,
                'goal' => 3840000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Joshua Giliard Mchaki',
                'member_number' => 'ASC44',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Joyce Mdoe',
                'member_number' => 'BA2',
                'membership' => 'Business Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Juliana Joseph',
                'member_number' => 'SCH21',
                'membership' => 'Scholar',
                'periodic_amount' => 58333.00,
                'goal' => 700000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Julieth njau',
                'member_number' => 'ASC6',
                'membership' => 'Associate',
                'periodic_amount' => 250000.00,
                'goal' => 3000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Julieth Samuel Materu',
                'member_number' => 'ASC24',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Julius Michael Mboya',
                'member_number' => 'ASC42',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 1500000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'JUMA JUMAPILI KITUTU',
                'member_number' => 'SCH27',
                'membership' => 'Scholar',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Kanti Ambrose Kimario',
                'member_number' => 'PRM1',
                'membership' => 'Promoter',
                'periodic_amount' => 120000.00,
                'goal' => 4320000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Karim Rajab',
                'member_number' => 'ASC70',
                'membership' => 'Associate',
                'periodic_amount' => 100000.00,
                'goal' => 1200000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Kelvin M. Mwita',
                'member_number' => 'FND3',
                'membership' => 'Founder',
                'periodic_amount' => 120000.00,
                'goal' => 1440000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Kulwa Mwita Mang\'ana',
                'member_number' => 'ORD7',
                'membership' => 'Ordinary',
                'periodic_amount' => 120000.00,
                'goal' => 5760000.00,
            ],
            [
                'name' => 'LIDYA INYASI MASSENGA',
                'member_number' => 'ASC52',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 1200000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Living Christopher koka',
                'member_number' => 'PRM4',
                'membership' => 'Promoter',
                'periodic_amount' => 250000.00,
                'goal' => 3000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Lumen lyaka kapulile',
                'member_number' => 'SCH18',
                'membership' => 'Scholar',
                'periodic_amount' => 20000.00,
                'goal' => 240000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Magdalena Joseph Mark',
                'member_number' => 'ASC78',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Magreth Mosha',
                'member_number' => 'ASC86',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Maria Geofrey Masawa',
                'member_number' => 'ASC64',
                'membership' => 'Associate',
                'periodic_amount' => 100000.00,
                'goal' => 1200000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Mary Andrea Marandu',
                'member_number' => 'ASC28',
                'membership' => 'Associate',
                'periodic_amount' => 555556.00,
                'goal' => 10000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Mary Mwinuka',
                'member_number' => 'FND1',
                'membership' => 'Founder',
                'periodic_amount' => 130000.00,
                'goal' => 7800000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Michael Nassoro Shabani',
                'member_number' => 'ASC53',
                'membership' => 'Associate',
                'periodic_amount' => 277778.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Michael Paul',
                'member_number' => 'ORD3',
                'membership' => 'Ordinary',
                'periodic_amount' => 120000.00,
                'goal' => 2880000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'MIRIAM RICHARD MHAGAMA',
                'member_number' => 'ASC84',
                'membership' => 'Associate',
                'periodic_amount' => 100000.00,
                'goal' => 1200000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Mkula Beateice Machumu',
                'member_number' => 'ORD1',
                'membership' => 'Ordinary',
                'periodic_amount' => 120000.00,
                'goal' => 1440000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Mshamu Machalila',
                'member_number' => 'ASC54',
                'membership' => 'Associate',
                'periodic_amount' => 1388889.00,
                'goal' => 50000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Mugisha Ntiyonza Nkoronko',
                'member_number' => 'ORD6',
                'membership' => 'Ordinary',
                'periodic_amount' => 250000.00,
                'goal' => 3000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'MUSSA ROBERT MATUNDWE',
                'member_number' => 'ASC51',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Mwamini Osward Bavuma',
                'member_number' => 'SCH10',
                'membership' => 'Scholar',
                'periodic_amount' => 20000.00,
                'goal' => 240000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Nestory Fratern Mrosso',
                'member_number' => 'ASC41',
                'membership' => 'Associate',
                'periodic_amount' => 277778.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Ngendo Chacha',
                'member_number' => 'ASC7',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Nuru Abdallah',
                'member_number' => 'ASC83',
                'membership' => 'Associate',
                'periodic_amount' => 83333.00,
                'goal' => 2000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Paschazia Malongo Sayi',
                'member_number' => 'ASC21',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Paul Reuben Mwinuka',
                'member_number' => 'ORD4',
                'membership' => 'Ordinary',
                'periodic_amount' => 41667.00,
                'goal' => 1500000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Penina Charles',
                'member_number' => 'SCH3',
                'membership' => 'Scholar',
                'periodic_amount' => 333333.00,
                'goal' => 2000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Peter Gasper Kweka',
                'member_number' => 'ASC124',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Peter Jonathan Mkande',
                'member_number' => 'ASC2',
                'membership' => 'Associate',
                'periodic_amount' => 416667.00,
                'goal' => 10000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Prisila Ambrosi Kimario',
                'member_number' => 'ASC37',
                'membership' => 'Associate',
                'periodic_amount' => 96667.00,
                'goal' => 2320000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Rachel chedy kafyulilo',
                'member_number' => 'SCH15',
                'membership' => 'Scholar',
                'periodic_amount' => 20000.00,
                'goal' => 240000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Rachel Yona Ngoko',
                'member_number' => 'SCH26',
                'membership' => 'Scholar',
                'periodic_amount' => 20000.00,
                'goal' => 240000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Rahabu D Mwakanyika',
                'member_number' => 'ASC76',
                'membership' => 'Associate',
                'periodic_amount' => 125000.00,
                'goal' => 3000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Ramadhani Kimangare',
                'member_number' => 'ASC34',
                'membership' => 'Associate',
                'periodic_amount' => 104167.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Raymond Buberwa',
                'member_number' => 'SCH19',
                'membership' => 'Scholar',
                'periodic_amount' => 20000.00,
                'goal' => 240000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Rebeka France Kaduma',
                'member_number' => 'SCH16',
                'membership' => 'Scholar',
                'periodic_amount' => 20000.00,
                'goal' => 240000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Regina ladslaus',
                'member_number' => 'SCH32',
                'membership' => 'Scholar',
                'periodic_amount' => 40000.00,
                'goal' => 480000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'REUBEN A. MWANDAMBO',
                'member_number' => 'ASC58',
                'membership' => 'Associate',
                'periodic_amount' => 83333.00,
                'goal' => 1000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Robert Kiwia',
                'member_number' => 'ASC119',
                'membership' => 'Associate',
                'periodic_amount' => 100000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Rozina Z Maro',
                'member_number' => 'ASC56',
                'membership' => 'Associate',
                'periodic_amount' => 166667.00,
                'goal' => 2000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Salua Haji Othman',
                'member_number' => 'ASC33',
                'membership' => 'Associate',
                'periodic_amount' => 416667.00,
                'goal' => 2500000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Samia Mustapha Msusa',
                'member_number' => 'SCH24',
                'membership' => 'Scholar',
                'periodic_amount' => 20000.00,
                'goal' => 240000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'SAMSON WILLIAM SINGANO',
                'member_number' => 'SCH36',
                'membership' => 'Scholar',
                'periodic_amount' => 83333.00,
                'goal' => 1000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Sapiencia Cyprian Mugarula',
                'member_number' => 'ASC25',
                'membership' => 'Associate',
                'periodic_amount' => 104167.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Sarah Yesaya Fungo',
                'member_number' => 'SCH29',
                'membership' => 'Scholar',
                'periodic_amount' => 54167.00,
                'goal' => 1300000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Sarah Richard Mhagama',
                'member_number' => 'ASC80',
                'membership' => 'Associate',
                'periodic_amount' => 360000.00,
                'goal' => 4320000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Sigfred A Ngereza',
                'member_number' => 'SCH2',
                'membership' => 'Scholar',
                'periodic_amount' => 125000.00,
                'goal' => 6000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Silla Ponziano Chaula',
                'member_number' => 'ASC23',
                'membership' => 'Associate',
                'periodic_amount' => 300000.00,
                'goal' => 3600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Stephene Augustino Lulandala',
                'member_number' => 'ASC72',
                'membership' => 'Associate',
                'periodic_amount' => 166667.00,
                'goal' => 4000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'SUZAN JOSEPH MKINGA',
                'member_number' => 'ASC39',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Sweetbeth Barnaba Mwacha',
                'member_number' => 'SCH35',
                'membership' => 'Scholar',
                'periodic_amount' => 304167.00,
                'goal' => 3650000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Swf',
                'member_number' => 'GRP3',
                'membership' => 'Group',
                'periodic_amount' => 1041667.00,
                'goal' => 50000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Theresia E. Materu',
                'member_number' => 'ASC66',
                'membership' => 'Associate',
                'periodic_amount' => 416667.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Tumeahidiwa Eliakimu Tweve',
                'member_number' => 'SCH39',
                'membership' => 'Scholar',
                'periodic_amount' => 20000.00,
                'goal' => 960000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Tumepewa Tweve',
                'member_number' => 'SCH12',
                'membership' => 'Scholar',
                'periodic_amount' => 291667.00,
                'goal' => 3500000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Upendo Ruben Mwinuka',
                'member_number' => 'ASC38',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'VAILETH JOHN MJAGAMA',
                'member_number' => 'ASC65',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Vancee Anthony Mbango',
                'member_number' => 'ASC4',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Victoria S.Mwambungu',
                'member_number' => 'ORD5',
                'membership' => 'Ordinary',
                'periodic_amount' => 120000.00,
                'goal' => 4320000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Weston Lemanya',
                'member_number' => 'ASC17',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'William Kaberege',
                'member_number' => 'FND5',
                'membership' => 'Founder',
                'periodic_amount' => 100000.00,
                'goal' => 1200000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Winnrose Elifuraha Mmari',
                'member_number' => 'ASC13',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Witness Clement Sam',
                'member_number' => 'SCH13',
                'membership' => 'Scholar',
                'periodic_amount' => 416667.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Witness Munisi',
                'member_number' => 'SCH40',
                'membership' => 'Scholar',
                'periodic_amount' => 520833.00,
                'goal' => 6250000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Yasinta mkichwe',
                'member_number' => 'ASC68',
                'membership' => 'Associate',
                'periodic_amount' => 125000.00,
                'goal' => 1500000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'RESPICK APOLINARY MMASY',
                'member_number' => 'SCH41',
                'membership' => 'Scholar',
                'periodic_amount' => 1142857.00,
                'goal' => 8000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Neema simon kilumbe',
                'member_number' => 'SCH42',
                'membership' => 'Scholar',
                'periodic_amount' => 83333.00,
                'goal' => 1000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'DAVID NGUNGILA',
                'member_number' => 'ASC108',
                'membership' => 'Associate',
                'periodic_amount' => 187500.00,
                'goal' => 1500000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Anno Massawe',
                'member_number' => 'ASC90',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'LULU ILOMO',
                'member_number' => 'ASC93',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Michael James Mwingwa',
                'member_number' => 'ASC94',
                'membership' => 'Associate',
                'periodic_amount' => 416667.00,
                'goal' => 10000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Calvin Mudy Moshi',
                'member_number' => 'SCH43',
                'membership' => 'Scholar',
                'periodic_amount' => 100000.00,
                'goal' => 1200000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Samson Niarira Mziray',
                'member_number' => 'ASC95',
                'membership' => 'Associate',
                'periodic_amount' => 125000.00,
                'goal' => 3000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Olipa Nicholaus',
                'member_number' => 'ASC96',
                'membership' => 'Associate',
                'periodic_amount' => 104167.00,
                'goal' => 2500000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'SEIF AHMAD LUYANGI',
                'member_number' => 'ASC98',
                'membership' => 'Associate',
                'periodic_amount' => 208333.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'RoseAugustino Bernard',
                'member_number' => 'ASC97',
                'membership' => 'Associate',
                'periodic_amount' => 166667.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Godfrey William Kaoneka',
                'member_number' => 'ASC100',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 2400000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Award John Award',
                'member_number' => 'ASC99',
                'membership' => 'Associate',
                'periodic_amount' => 208333.00,
                'goal' => 10000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Alex Jacob Ringo',
                'member_number' => 'ASC101',
                'membership' => 'Associate',
                'periodic_amount' => 138889.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Faustina Moses Kasebele',
                'member_number' => 'ASC102',
                'membership' => 'Associate',
                'periodic_amount' => 83333.00,
                'goal' => 3000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Alika Antony mbilinyi',
                'member_number' => 'ASC103',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 1200000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Rahabu Epro Mjila',
                'member_number' => 'SCH44',
                'membership' => 'Scholar',
                'periodic_amount' => 25000.00,
                'goal' => 300000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'GLORIA WILSON NGONDE',
                'member_number' => 'ASC104',
                'membership' => 'Associate',
                'periodic_amount' => 10000.00,
                'goal' => 200000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'DAMIANA RICHARD KUMBURU',
                'member_number' => 'SCH45',
                'membership' => 'Scholar',
                'periodic_amount' => 62500.00,
                'goal' => 1500000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'LINUS ABELI THEOBALD',
                'member_number' => 'ASC105',
                'membership' => 'Associate',
                'periodic_amount' => 166667.00,
                'goal' => 2000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Joyce sanzala',
                'member_number' => 'ASC92',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 1200000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Reuben Kalist Mdaheranwa',
                'member_number' => 'ASC106',
                'membership' => 'Associate',
                'periodic_amount' => 200000.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Apolinari Elias Herman',
                'member_number' => 'ASC107',
                'membership' => 'Associate',
                'periodic_amount' => 138889.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'lusia Eugen Chuwa',
                'member_number' => 'SCH46',
                'membership' => 'Scholar',
                'periodic_amount' => 138889.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Brayan lyaruu',
                'member_number' => 'SCH48',
                'membership' => 'Scholar',
                'periodic_amount' => 208333.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Consolatha Boniphace Shunashu',
                'member_number' => 'SCH49',
                'membership' => 'Scholar',
                'periodic_amount' => 41667.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Edward P. Sulle',
                'member_number' => 'SCH50',
                'membership' => 'Scholar',
                'periodic_amount' => 20833.00,
                'goal' => 1000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Hawa Hamadi Swai',
                'member_number' => 'ASC109',
                'membership' => 'Associate',
                'periodic_amount' => 75000.00,
                'goal' => 900000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'MUSSA NURRUDINI ABDALLAH',
                'member_number' => 'ASC110',
                'membership' => 'Associate',
                'periodic_amount' => 100000.00,
                'goal' => 1200000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Niwaeli Godwin Foy',
                'member_number' => 'SCH51',
                'membership' => 'Scholar',
                'periodic_amount' => 20833.00,
                'goal' => 1000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Sarapia Onespory Malyawere',
                'member_number' => 'SCH52',
                'membership' => 'Scholar',
                'periodic_amount' => 277778.00,
                'goal' => 10000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Silvia felix marandu',
                'member_number' => 'ASC111',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'FURAHA REUBEN',
                'member_number' => 'GRP2',
                'membership' => 'Group',
                'periodic_amount' => 100000.00,
                'goal' => 1200000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Marysedes George Msemwa',
                'member_number' => 'ASC89',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Rosemary katabi',
                'member_number' => 'ASC91',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'SIEMA',
                'member_number' => 'GRP1',
                'membership' => 'Group',
                'periodic_amount' => 100000.00,
                'goal' => 1200000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Magreth',
                'member_number' => 'SCH53',
                'membership' => 'Scholar',
                'periodic_amount' => 208333.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Roida Martin',
                'member_number' => 'SCH54',
                'membership' => 'Scholar',
                'periodic_amount' => 33333.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Joseph Daniel Zakaria',
                'member_number' => 'ASC112',
                'membership' => 'Associate',
                'periodic_amount' => 250000.00,
                'goal' => 3000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Christina Andrea Mang\'Ombe',
                'member_number' => 'ASC113',
                'membership' => 'Associate',
                'periodic_amount' => 83333.00,
                'goal' => 1000000.00,
            ],
            [
                'name' => 'Joyce Hiyata Maiko',
                'member_number' => 'ASC115',
                'membership' => 'Associate',
                'periodic_amount' => 83333.00,
                'goal' => 1000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Sarafina Frank Mfikwa',
                'member_number' => 'ASC114',
                'membership' => 'Associate',
                'periodic_amount' => 70000.00,
                'goal' => 840000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Yustina Andason Ngereza',
                'member_number' => 'ASC117',
                'membership' => 'Associate',
                'periodic_amount' => 83333.00,
                'goal' => 1000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Lea Simon Mlangali',
                'member_number' => 'ASC118',
                'membership' => 'Associate',
                'periodic_amount' => 83333.00,
                'goal' => 1000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Said chananja',
                'member_number' => 'SCH56',
                'membership' => 'Scholar',
                'periodic_amount' => 30303.00,
                'goal' => 1000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Gift John Swati',
                'member_number' => 'SCH55',
                'membership' => 'Scholar',
                'periodic_amount' => 166667.00,
                'goal' => 2000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Weo Imc Saving Plan',
                'member_number' => 'GRP4',
                'membership' => 'Group',
                'periodic_amount' => 1166667.00,
                'goal' => 14000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Neema Emmanuel Mria',
                'member_number' => 'SCH58',
                'membership' => 'Scholar',
                'periodic_amount' => 41667.00,
                'goal' => 2000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Lukelo Neno Lulandala',
                'member_number' => 'SCH57',
                'membership' => 'Scholar',
                'periodic_amount' => 83333.00,
                'goal' => 2000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Fibi Saitoti Lemanga',
                'member_number' => 'SCH59',
                'membership' => 'Scholar',
                'periodic_amount' => 2083333.00,
                'goal' => 50000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Jenifa Christian Tairo',
                'member_number' => 'ASC123',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 900000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Grace Ndomba',
                'member_number' => 'SCH60',
                'membership' => 'Scholar',
                'periodic_amount' => 62500.00,
                'goal' => 1500000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Flora Jacob Odhiambo',
                'member_number' => 'ASC125',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Anna Pius Moshiro',
                'member_number' => 'SCH61',
                'membership' => 'Scholar',
                'periodic_amount' => 83333.00,
                'goal' => 2000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Teresia Anthony Mwakampya',
                'member_number' => 'SCH62',
                'membership' => 'Scholar',
                'periodic_amount' => 4167.00,
                'goal' => 150000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Judith Shao',
                'member_number' => 'SCH63',
                'membership' => 'Scholar',
                'periodic_amount' => 83333.00,
                'goal' => 3000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Tumaini Hashim Yarumba',
                'member_number' => 'ASC126',
                'membership' => 'Associate',
                'periodic_amount' => 83333.00,
                'goal' => 3000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Sebastian Paschal Mbwaga',
                'member_number' => 'SCH64',
                'membership' => 'Scholar',
                'periodic_amount' => 33333.00,
                'goal' => 1200000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Fredrick Cleophace Nzumbi',
                'member_number' => 'ASC129',
                'membership' => 'Associate',
                'periodic_amount' => 416667.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'IRENE SAMWEL MBISE',
                'member_number' => 'SCH65',
                'membership' => 'Scholar',
                'periodic_amount' => 40000.00,
                'goal' => 2000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Suzana Bahaye Mika',
                'member_number' => 'ASC130',
                'membership' => 'Associate',
                'periodic_amount' => 69444.00,
                'goal' => 2500000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Everlyine Nyambane',
                'member_number' => 'SCH68',
                'membership' => 'Scholar',
                'periodic_amount' => 83333.00,
                'goal' => 1000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Adelius Sostenes Pastory',
                'member_number' => 'SCH66',
                'membership' => 'Scholar',
                'periodic_amount' => 5000.00,
                'goal' => 500000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Vicent Simon Gabriel',
                'member_number' => 'SCH69',
                'membership' => 'Scholar',
                'periodic_amount' => 20000.00,
                'goal' => 1900000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Twilumba Justine Mfugale',
                'member_number' => 'SCH67',
                'membership' => 'Scholar',
                'periodic_amount' => 20000.00,
                'goal' => 500000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Petro Ngalu',
                'member_number' => 'ASC131',
                'membership' => 'Associate',
                'periodic_amount' => 50000.00,
                'goal' => 1000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Glory Mathew Ulomi',
                'member_number' => 'SCH70',
                'membership' => 'Scholar',
                'periodic_amount' => 250000.00,
                'goal' => 3000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Baraka mria',
                'member_number' => 'ASC134',
                'membership' => 'Associate',
                'periodic_amount' => 277778.00,
                'goal' => 10000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Christopher Ezekiel Msigala',
                'member_number' => 'ASC133',
                'membership' => 'Associate',
                'periodic_amount' => 100000.00,
                'goal' => 10000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Joachim Malulu',
                'member_number' => 'ASC135',
                'membership' => 'Associate',
                'periodic_amount' => 416667.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Gloria Michael Shine',
                'member_number' => 'SCH71',
                'membership' => 'Scholar',
                'periodic_amount' => 54167.00,
                'goal' => 650000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Raheli Mahali',
                'member_number' => 'SCH73',
                'membership' => 'Scholar',
                'periodic_amount' => 20833.00,
                'goal' => 500000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Ronald E. Chibanda',
                'member_number' => 'ASC137',
                'membership' => 'Associate',
                'periodic_amount' => 857143.00,
                'goal' => 12000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Fredrick Michael Wangabo',
                'member_number' => 'SCH74',
                'membership' => 'Scholar',
                'periodic_amount' => 138889.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'BERNADETA CHIKOTI',
                'member_number' => 'ASC139',
                'membership' => 'Associate',
                'periodic_amount' => 833333.00,
                'goal' => 50000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Samsoni Paulo Muro',
                'member_number' => 'SCH78',
                'membership' => 'Scholar',
                'periodic_amount' => 100000.00,
                'goal' => 10000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Nelson Prosper Kimosso',
                'member_number' => 'ASC141',
                'membership' => 'Associate',
                'periodic_amount' => 164835.00,
                'goal' => 15000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Ester Ernest Mnzava',
                'member_number' => 'ASC142',
                'membership' => 'Associate',
                'periodic_amount' => 100000.00,
                'goal' => 1000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Damian Gabriel Assenga',
                'member_number' => 'ASC140',
                'membership' => 'Associate',
                'periodic_amount' => 62500.00,
                'goal' => 500000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Fransiska Mrina',
                'member_number' => 'SCH77',
                'membership' => 'Scholar',
                'periodic_amount' => 83333.00,
                'goal' => 1000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Jeremia Thomas Zacharia',
                'member_number' => 'SCH79',
                'membership' => 'Scholar',
                'periodic_amount' => 833333.00,
                'goal' => 10000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Kasian Jacob Makasi',
                'member_number' => 'ASC127',
                'membership' => 'Associate',
                'periodic_amount' => 250000.00,
                'goal' => 10000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Angela Twinamungu Godwini',
                'member_number' => 'SCH80',
                'membership' => 'Scholar',
                'periodic_amount' => 166667.00,
                'goal' => 2000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Filbert Joseph Mwampashe',
                'member_number' => 'ASC128',
                'membership' => 'Associate',
                'periodic_amount' => 600000.00,
                'goal' => 10000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Faraja shupa',
                'member_number' => 'ASC144',
                'membership' => 'Associate',
                'periodic_amount' => 416667.00,
                'goal' => 10000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Jesca Nickson Kisanga',
                'member_number' => 'ASC143',
                'membership' => 'Associate',
                'periodic_amount' => 416667.00,
                'goal' => 10000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Remijo Msigwa',
                'member_number' => 'SCH82',
                'membership' => 'Scholar',
                'periodic_amount' => 20833.00,
                'goal' => 500000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Aliakber M Moledina',
                'member_number' => 'SCH81',
                'membership' => 'Scholar',
                'periodic_amount' => 250000.00,
                'goal' => 12000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Besiphage Johan Mwambeso',
                'member_number' => 'SCH83',
                'membership' => 'Scholar',
                'periodic_amount' => 208333.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Mbaraka A. Nabaraka',
                'member_number' => 'ASC145',
                'membership' => 'Associate',
                'periodic_amount' => 208333.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Ivona Bailemba',
                'member_number' => 'SCH84',
                'membership' => 'Scholar',
                'periodic_amount' => 166667.00,
                'goal' => 1000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Costansia Mosha',
                'member_number' => 'SCH85',
                'membership' => 'Scholar',
                'periodic_amount' => 125000.00,
                'goal' => 1500000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Emilia Modest Bura',
                'member_number' => 'SCH86',
                'membership' => 'Scholar',
                'periodic_amount' => 50000.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Nasri Issa',
                'member_number' => 'SCH87',
                'membership' => 'Scholar',
                'periodic_amount' => 208333.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'ANGELISTA EDES MODEST',
                'member_number' => 'SCH88',
                'membership' => 'Scholar',
                'periodic_amount' => 83333.00,
                'goal' => 2000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Asteria Adriano Anthony',
                'member_number' => 'SCH89',
                'membership' => 'Scholar',
                'periodic_amount' => 50000.00,
                'goal' => 600000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'Clemence John Mjujulu',
                'member_number' => 'SCH90',
                'membership' => 'Scholar',
                'periodic_amount' => 208333.00,
                'goal' => 5000000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
            [
                'name' => 'PASCHAL M. PANGA',
                'member_number' => 'ASC146',
                'membership' => 'Associate',
                'periodic_amount' => 200000.00,
                'goal' => 2400000.00,
                'period_type' => 'monthly',
                'period_value' => 12,
                'status' => 'active',
            ],
        ];

        foreach ($savingPlansData as $savingPlan) {
            DB::table('saving_plans')->insert($savingPlan);
        }

        // Re-enable foreign key constraints
        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        $this->command->info('Saving plan seeder completed successfully. ' . count($savingPlansData) . ' saving plans seeded.');
    }
}
