<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TransactionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key constraints
        DB::statement('SET FOREIGN_KEY_CHECKS=0');

        // Clear existing transactions
        DB::table('transactions')->truncate();

        $transactionsData = [
            [
                'date' => '2025-03-01',
                'membercode' => 'FND1',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 24158.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC75',
                'transaction_type' => 'RDA-Withdrawal',
                'reference_no' => 'IB79268101032611',
                'amount' => -400000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'GRP3',
                'transaction_type' => 'RDA-Withdrawal',
                'reference_no' => 'IB79239201032610 -Charity',
                'amount' => -200000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH55',
                'transaction_type' => 'RDA-Withdrawal',
                'reference_no' => '403IBFT260600009',
                'amount' => -3000000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH55',
                'transaction_type' => 'Flexi-Withdrawal',
                'reference_no' => '403IBFT260600009',
                'amount' => -100000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH41',
                'transaction_type' => 'RDA-Withdrawal',
                'reference_no' => '403OPIB260600501',
                'amount' => -1630000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH41',
                'transaction_type' => 'Flexi-Withdrawal',
                'reference_no' => '403OPIB260600501',
                'amount' => -250000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC129',
                'transaction_type' => 'Flexi-Deposit',
                'reference_no' => '19ca9cdada b52b8f',
                'amount' => 100000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'FND2',
                'transaction_type' => 'RDA-Deposit',
                'reference_no' => 'IB79677801 032616',
                'amount' => 250000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC64',
                'transaction_type' => 'RDA-Deposit',
                'reference_no' => 'IB79677801 032616',
                'amount' => 200000.00,
            ],
            [
                'date' => '2026-03-02',
                'membercode' => 'SCH51',
                'transaction_type' => 'Flexi-Withdrawal',
                'reference_no' => '6060590156250010',
                'amount' => -400000.00,
            ],
            [
                'date' => '2026-03-02',
                'membercode' => 'ASC16',
                'transaction_type' => 'Flexi-Deposit',
                'reference_no' => '19cae9ebd5ed1833',
                'amount' => 600000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC135',
                'transaction_type' => 'RDA-Deposit',
                'reference_no' => '19ca7d82846b7b3b',
                'amount' => 350000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC135',
                'transaction_type' => 'Flexi-Deposit',
                'reference_no' => '19ca7deadb2d7b26',
                'amount' => 20000.00,
            ],
            [
                'date' => '2026-03-02',
                'membercode' => 'PRM2',
                'transaction_type' => 'RDA-Deposit',
                'reference_no' => 'IB84361602 032623',
                'amount' => 198000.00,
            ],
            [
                'date' => '2026-03-03',
                'membercode' => 'ASC107',
                'transaction_type' => 'RDA-Deposit',
                'reference_no' => 'MKFT1251RM MA9EFPICP9ECE',
                'amount' => 100000.00,
            ],
            [
                'date' => '2026-03-03',
                'membercode' => 'ASC129',
                'transaction_type' => 'Flexi-Deposit',
                'reference_no' => '19cb4ae8ec 1739d0',
                'amount' => 1110000.00,
            ],
            [
                'date' => '2026-03-03',
                'membercode' => 'ASC120',
                'transaction_type' => 'Emmergence-Deposit',
                'reference_no' => '101AGD2260 62G1GO',
                'amount' => 100000.00,
            ],
            [
                'date' => '2026-03-04',
                'membercode' => 'ASC122',
                'transaction_type' => 'Flexi-Deposit',
                'reference_no' => '19cb7bf707 ce3a33',
                'amount' => 200000.00,
            ],
            [
                'date' => '2026-03-04',
                'membercode' => 'ASC75',
                'transaction_type' => 'RDA-Deposit',
                'reference_no' => '19cb7b7dc1 83f82f',
                'amount' => 100000.00,
            ],
            [
                'date' => '2026-03-04',
                'membercode' => 'ASC16',
                'transaction_type' => 'Flexi-Withdrawal',
                'reference_no' => '19cb9f827db47b6a',
                'amount' => -5000000.00,
            ],
            [
                'date' => '2026-03-05',
                'membercode' => 'SCH69',
                'transaction_type' => 'Flexi-Deposit',
                'reference_no' => '19cbe9d648 c48c4e911',
                'amount' => 10000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH12',
                'transaction_type' => 'Flexi-Deposit',
                'reference_no' => '19cbf24fc 2387912',
                'amount' => 50000.00,
            ],
            [
                'date' => '2026-03-03',
                'membercode' => 'ASC126',
                'transaction_type' => 'Flexi-Deposit',
                'reference_no' => '19c8b74d3f7929e6',
                'amount' => 40950.39,
            ],
            [
                'date' => '2026-03-06',
                'membercode' => 'ASC137',
                'transaction_type' => 'RDA-Deposit',
                'reference_no' => '19cc18d7a0 0e3958',
                'amount' => 150000.00,
            ],
            [
                'date' => '2026-03-06',
                'membercode' => 'SCH49',
                'transaction_type' => 'Flexi-Deposit',
                'reference_no' => 'MP2603 06.0903.M14950',
                'amount' => 7000.00,
            ],
            [
                'date' => '2026-03-06',
                'membercode' => 'SCH64',
                'transaction_type' => 'Flexi-Deposit',
                'reference_no' => '19cc249e3f 1a2b7a',
                'amount' => 20000.00,
            ],
            [
                'date' => '2026-03-05',
                'membercode' => 'SCH75',
                'transaction_type' => 'Flexi-Deposit',
                'reference_no' => '19cbe9b82e 6b39a8',
                'amount' => 80000.00,
            ],
            [
                'date' => '2026-03-06',
                'membercode' => 'ASC66',
                'transaction_type' => 'RDA-Withdrawal',
                'reference_no' => 'IB99277606032621',
                'amount' => -2600000.00,
            ],
            [
                'date' => '2026-03-06',
                'membercode' => 'ASC66',
                'transaction_type' => 'Flexi-Withdrawal',
                'reference_no' => 'IB99277606032621',
                'amount' => -1500000.00,
            ],
            [
                'date' => '2026-03-07',
                'membercode' => 'PRM4',
                'transaction_type' => 'Flexi-Deposit',
                'reference_no' => '19cc7f3153555ab3',
                'amount' => 600000.00,
            ],
            [
                'date' => '2026-03-06',
                'membercode' => 'SCH12',
                'transaction_type' => 'RDA-Deposit',
                'reference_no' => '19cc78e105 f1197d',
                'amount' => 500000.00,
            ],
            [
                'date' => '2026-03-07',
                'membercode' => 'PRM4',
                'transaction_type' => 'Flexi-Deposit',
                'reference_no' => '19cc8ba48176396e',
                'amount' => 150000.00,
            ],
            [
                'date' => '2026-03-07',
                'membercode' => 'SCH58',
                'transaction_type' => 'Flexi-Deposit',
                'reference_no' => '26894385361758',
                'amount' => 85000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'FND1',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 806077.25,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'FND2',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 6887856.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'PRM2',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 26567566.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC1',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 500000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ORD2',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1171866.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC6',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 2111924.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC9',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 5859.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC10',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 688630.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC12',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 391161.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH2',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 3289842.00,
            ],
            [
                'date' => '2026-03-14',
                'membercode' => 'ASC137',
                'transaction_type' => 'RDA-Deposit',
                'reference_no' => '19ceab5d8 5e7829',
                'amount' => 100000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH12',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1225188.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC17',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 332000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'FND5',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 436934.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH13',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 2103558.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC26',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1251007.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC35',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 7845187.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC36',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 6807530.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC46',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 54188.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC53',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 5073.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC54',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 16059531.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC55',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1245457.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC64',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 2500000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC66',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 2660864.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC68',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 911360.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC69',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 8488349.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC72',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1804139.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC73',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 422837.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC74',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1100000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC75',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 3354974.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC76',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1350000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC77',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 114300.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC80',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 2775.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH40',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1614603.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC86',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 200000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH41',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1636576.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH42',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 900000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC96',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 9000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC98',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1330000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC101',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 16223.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH45',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 91000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC105',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 2620000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC107',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1850419.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC108',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 754000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH53',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1000000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'GRP3',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 9310297.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC112',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1700000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC117',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1650500.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH55',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 3000000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC120',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 522450.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'GRP4',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 10007408.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH57',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 800000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC122',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 2370000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC124',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 54473.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC125',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 450000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC126',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 100000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC127',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 100000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC128',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 515000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC131',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 200000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC132',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 500000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC133',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 100000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC134',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1000000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC136',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1000000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC137',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1800000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'FND1',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 515551.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ORD1',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 9746.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'PRM1',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 3316790.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'FND2',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 195871.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'PRM2',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 356897.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC1',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 432759.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC2',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 28028.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC3',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 31466.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC4',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 24338.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ORD2',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 25000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC6',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 146545.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC9',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 408909.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC10',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 3355557.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC11',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 530406.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC13',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 893515.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC14',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 143794.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH2',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 892562.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH3',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 2418.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH4',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 265799.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH5',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 12169.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH7',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 95578.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH8',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 95876.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH9',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1344.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH10',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 171803.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC16',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 16881108.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH12',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 799469.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC17',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 924200.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC18',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 42000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'FND4',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 58577.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC19',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 75053.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC20',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 26633.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'FND5',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1034618.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH13',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1450353.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC22',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 257732.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC23',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 113.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'FND6',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 461717.16,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC25',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 373615.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC26',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 20226438.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC27',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1428.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC29',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1024.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC31',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 164087.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC33',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 364765.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC34',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 364449.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC35',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 610562.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC36',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 690970.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC37',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1433246.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC38',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 957351.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ORD4',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1833359.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC39',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 364703.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC40',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 39495.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC42',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 985492.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ORD5',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 734128.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC43',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 712172.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC46',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 112010.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC47',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 188555.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'PRM4',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 3627674.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'FND7',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 5514735.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'PRM5',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1994569.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC52',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 129138.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC53',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => -362.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC55',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 572056.00,
            ],
            [
                'date' => '2026-03-05',
                'membercode' => 'SCH73',
                'transaction_type' => 'Flexi-Deposit',
                'reference_no' => 'DC52NAWOHV0',
                'amount' => 21000.00,
            ],
            [
                'date' => '2026-03-09',
                'membercode' => 'SCH54',
                'transaction_type' => 'Emmergence-Withdrawal',
                'reference_no' => '26194801875243.00',
                'amount' => -90000.00,
            ],
            [
                'date' => '2026-03-09',
                'membercode' => 'PRM2',
                'transaction_type' => 'RDA-Deposit',
                'reference_no' => 'IB14477709 032618',
                'amount' => 810000.00,
            ],
            [
                'date' => '2026-03-07',
                'membercode' => 'PRM1',
                'transaction_type' => 'Flexi-Deposit',
                'reference_no' => 'Admin payment-Feb 2026',
                'amount' => 66000.00,
            ],
            [
                'date' => '2026-03-07',
                'membercode' => 'SCH2',
                'transaction_type' => 'RDA-Deposit',
                'reference_no' => 'Admin payment-Feb 2026',
                'amount' => 100969.00,
            ],
            [
                'date' => '2026-03-07',
                'membercode' => 'SCH2',
                'transaction_type' => 'Emmergence-Deposit',
                'reference_no' => 'Admin payment-Feb 2026',
                'amount' => 65000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC57',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 523536.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC58',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 827448.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC60',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 13595.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH15',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 10698.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH16',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 35843.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH17',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 12081.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH19',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 24355.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH21',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 6065.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC62',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 27691.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC63',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 425771.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC64',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 703568.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH26',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 6250.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC65',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 322691.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH29',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 8270.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH30',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1367.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH31',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 147395.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC66',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1586346.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC68',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 91369.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH32',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 806.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC69',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 87383.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC71',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 32013.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC72',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 37505.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC73',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 3061012.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC74',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1137558.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC75',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 132203.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH35',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 34543.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH36',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 225.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC76',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 940465.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC77',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 468109.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH37',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 4032.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC79',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 513106.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC80',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 619326.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH38',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 65880.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH39',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 41889.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC81',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => -17363.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC83',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 40789.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC84',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 40252.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC85',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1556830.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH40',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => -1589607.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC86',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 270510.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC87',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 381330.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC88',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 697.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH41',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 257848.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC89',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 478456.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC90',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 20818.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH42',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 25677.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC91',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 10403.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC92',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 10478.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC94',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 10431.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC96',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 110758.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC98',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 94161.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC99',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 11383.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC100',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 60304.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC101',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 48258.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC102',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 35890.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH44',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 13966.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC104',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 149765.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH45',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 20594.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC105',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 643056.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC106',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 15728.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH46',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1011.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC107',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 192792.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'GRP1',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1009952.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH48',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 41029.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC108',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 593756.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH49',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 10942.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH50',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 212611.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC110',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => -50000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH51',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 407234.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH52',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 282438.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ORD7',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 330278.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ORD8',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 850.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ORD9',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 188550.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ORD10',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 756072.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH53',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1366534.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH54',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 28801.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'GRP3',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 883420.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC113',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 19896.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC114',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 50635.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC116',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 105333.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC117',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 416779.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC118',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 83802.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC119',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 670932.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH55',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 113134.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH56',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 928.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC120',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 242811.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH57',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 101201.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH58',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1350000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC122',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 965145.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH59',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 5105.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC123',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 93042.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC124',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 22706.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH60',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 36135.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH61',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 34032.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH62',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 51646.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH63',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 503288.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC126',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 3543920.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH64',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 277509.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC127',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 150000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC129',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 1106904.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH65',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 80606.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC130',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 486011.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH67',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 244139.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH68',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 15108.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH69',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 20000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH70',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 125921.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC131',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 81161.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC134',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 5945.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC135',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 644262.00,
            ],
            [
                'date' => '2026-03-10',
                'membercode' => 'ASC129',
                'transaction_type' => 'Flexi-Deposit',
                'reference_no' => '19cd85a14a 0dfa7c',
                'amount' => 30000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH71',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 55000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC137',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 50000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH74',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 7300.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH75',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 100000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC81',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 17363.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'FND2',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 311400.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'FND4',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 25000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC34',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 5000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ORD4',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 120580.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ORD5',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 137997.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'FND7',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 550000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC57',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 528537.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH29',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 400.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC66',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 30784.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH39',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 30000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC93',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 490000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC108',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 23794.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC110',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 57000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH52',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 5000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'GRP2',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 200000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'SCH54',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 267002.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC120',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 5000.00,
            ],
            [
                'date' => '2026-03-01',
                'membercode' => 'ASC122',
                'transaction_type' => 'Opening Balance',
                'reference_no' => 'Opening balance',
                'amount' => 328500.00,
            ],
            [
                'date' => '2026-03-08',
                'membercode' => 'ASC69',
                'transaction_type' => 'RDA-Deposit',
                'reference_no' => '19ccd4e8d2 b02a80',
                'amount' => 350000.00,
            ],
            [
                'date' => '2026-03-07',
                'membercode' => 'SCH50',
                'transaction_type' => 'Flexi-Deposit',
                'reference_no' => '26894399106438',
                'amount' => 150000.00,
            ],
            [
                'date' => '2026-03-07',
                'membercode' => 'GRP3',
                'transaction_type' => 'Flexi-Deposit',
                'reference_no' => 'Admin payment Feb 2026-Sigfred',
                'amount' => 72000.00,
            ],
            [
                'date' => '2026-03-07',
                'membercode' => 'SCH13',
                'transaction_type' => 'Flexi-Deposit',
                'reference_no' => 'Admin payment-Feb 2026',
                'amount' => 124361.00,
            ],
        ];

        foreach ($transactionsData as $transaction) {
            DB::table('transactions')->insert($transaction);
        }

        // Re-enable foreign key constraints
        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        $this->command->info('Transaction seeder completed successfully. ' . count($transactionsData) . ' transactions seeded.');
    }
}
